### ISSUE TITLE
Extra scrollbar in banner

### ISSUE THREAD

**Issue by Rplus** [adobe-fonts/source-han-serif#10]
There is an extra scrollbar in banner when browser width is around 500px ~ 768px

https://source.typekit.com/source-han-serif/
![image](https://cloud.githubusercontent.com/assets/1808835/24688540/2a69ed74-19f3-11e7-966a-e59f3a75e816.png)

---

Workaround 1:
remove `padding-bottom: 0` for `.banner`, or set a other value of scrollbar width
![image](https://cloud.githubusercontent.com/assets/1808835/24688633/b2ec22e8-19f3-11e7-97ce-471eaf2962e1.png)

Workaround 2:
use `flexbox` & `flex-wrap` for `.banner` layout. ;)

**Comment by kenlunde** [comment]
Thank you. Because this is not an issue with the fonts themselves, I am closing it. It will be reported to the appropriate person, though.

**Comment by miguelsousa** [comment]
@wentin
