### ISSUE TITLE
Missing Glyphs in CN Subset like 霜, 雪, 需, etc.

### ISSUE THREAD

**Issue by p03tgqxm** [adobe-fonts/source-han-serif#106]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for Chinese mainland, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description
![image](https://user-images.githubusercontent.com/43498546/138797794-f1e71b63-7ef5-49fe-98d0-dbfbe530cd46.png)
Glyphs like 霜, 雪, 需, etc is missing in **CN subset** in Version 2.000R.

**Comment by MY1L** [comment]
Glyphs like 箭, etc is missing in SourceHanSerifCN-VF.ttf, Version 2.000
added.
