### ISSUE TITLE
Incorrect mappings of 5 全-composed characters for HK and TW

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#109]
As title. For TW and HK, the upper part of the 全 component should be a 入, not 人. They are not unifiable. Five codepoints are affected:

![cyun](https://user-images.githubusercontent.com/959433/138804541-39616409-0ab8-41b7-a214-70d907efc8e1.png)

| # | Codepoint | Current glyph | | Remap suggestion |
| --| ------------| ----------------| - | ------------------ |
| 1 | U+5168 全 | uni5168-JP | -> | uni5168uE0101-JP |
| 2 | U+6D24 洤 | uni6D24-CN | -> | uni6D24-JP |
| 3 | U+8DE7 跧 | uni8DE7-CN | -> | uni8DE7-JP | 
| 4 | U+8F07 輇 | uni8F07-CN | -> | uni8F07-JP | 
| 5 | U+9293 銓 | uni9293-CN | -> | uni9293-JP |

I am aware that the font is using two slightly different designs for JP/KR and TW/HK, like below:

![cyun2](https://user-images.githubusercontent.com/959433/138804905-c6cfd4be-3d7c-4b65-a692-4492b2db670d.png)

The only difference is the length of the horizontal line of 入 (TW/HK is slightly shorter). This, to me, is actually a unifiable difference. Which is why I am not suggesting new glyphs be added.

**Comment by Marcus98T** [comment]
Well as of 2.001, I have verified the fix, except for 牷 and maybe some others. I suppose in the next version, I suggest mapping those characters to JP/KR forms if all components are unifiable, that is.

**Comment by punchcutter** [comment]
This original issue was addressed a long time ago so closing this. The additional comments after that can be looked at as part of a new issue if necessary.

**Comment by Marcus98T** [comment]
> The additional comments after that can be looked at as part of a new issue if necessary.

@punchcutter Which is exactly why [I already made a new issue regarding the additional 全 mappings](https://github.com/adobe-fonts/source-han-sans/issues/414#issuecomment-1571649999). This can be seen as a continuation of this closed issue.
