### ISSUE TITLE
Glyph issues regarding 彳(U+5F73), 民(U+6C11, TW & CN) and 魘 (U+9B58, JP & KR)

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#11]
### A. 彳 (U+5F73)

彳 (U+5F73) is a word, so its glyph is supposed to be centre-aligned instead of offseted to the left. The same happens to Source Han Sans and had been reported before. 

![shserif-5f73](https://cloud.githubusercontent.com/assets/959433/24689419/01026ffa-19f9-11e7-816e-0d987853f1a6.png)

### B. 民 (U+6C11, TW & CN)

![shserif-6c11](https://cloud.githubusercontent.com/assets/959433/24689461/4d9721a8-19f9-11e7-8be4-58a446f8261e.png)

The overall position of 民 (U+6C11) in TW/CN stays the same as JP/KR despite the stroke difference. This causes the glyph look unbalaned. Again, this had also been reported before in the Source Han Sans issue tracker.

### C. 魘 (U+9B58, JP & KR)

![shserif-9f58](https://cloud.githubusercontent.com/assets/959433/24689547/dea12c34-19f9-11e7-82f9-5cf0bb375af7.png)

There is an issue with the interpolation of 魘 (U+9B58) for JP and KR.

**Comment by kenlunde** [comment]
Thank you. Yes, A and B are also on the hook for addressing in _Source Han Sans_. C has been confirmed.

**Comment by kenlunde** [comment]
The issue for 彳 U+5F73 is best addressed by shifting its glyph, _uni5F73-CN_, to be centered within the em-box. (It also may benefit from being made a bit wider.) The issue for 民 U+6C11 is more subtle, and requires that its glyph, _uni6C11-VN_, be better balanced within the em-box. I will leave the details to the discretion of the typeface designer.

**Comment by kenlunde** [comment]
Consolidated with Issue #27.
