### ISSUE TITLE
Extra Little Nubbin (Serif?) on 採 in Korean Version of Source Han Serif

### ISSUE THREAD

**Issue by pan-asian-wok** [adobe-fonts/source-han-serif#118]
Forgive me as I am probably not using the correct terminology, but I noticed this extra little nubbin (serif?) on the character 採 that does not appear in other words with the 采 component on the right side. This affects the Korean version of Source Han Serif in all weights, present and past versions. Please see the example before. Thank you for these fonts and congratulations on the release of Source Han Serif 2.0!

![Extra Little Nubbin](https://user-images.githubusercontent.com/45274474/139008390-d11d8e8f-d4e1-4f03-b41f-5ee97a272582.JPG)

**Comment by punchcutter** [comment]
Fixed in 2.001
