### ISSUE TITLE
Incorrect mappings of characters with the component 戶 in TC version

### ISSUE THREAD

**Issue by gbnewb** [adobe-fonts/source-han-serif#119]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

![image](https://user-images.githubusercontent.com/88551948/139283463-57db02de-73e4-4528-b540-723546be8f92.png)

They should all be 戶 according to TW standard. I just picked a few of them to show the problem. All characters with 戶 should be checked to completely fix the problem.

This problem is too obvious... I don't know why it even happened in the first place.
BTW incorrect mappings are all over the place when I try to read anything in this 2.0 version. Incorrect mappings of common components like 戶，入，以 affect so many characters. These issues have been opened by other people.
This 2.000 version really needs refining.

**Comment by NightFurySL2001** [comment]
HK version exist the same problems too. It seems mappings for JP -> TW/HK are missing (my guess is a lost/misplaced file while building resources).

**Comment by punchcutter** [comment]
Fixed in 2.001.
