### ISSUE TITLE
about font name, family and style

### ISSUE THREAD

**Issue by CNMan** [adobe-fonts/source-han-serif#12]
![name](https://i.imgur.com/hsXFGkV.png)

![familystyle](https://i.imgur.com/gm35QFy.png)

**Comment by kenlunde** [comment]
The Regular weight is style-linked to the Bold weight, so this is expected. When using these fonts in apps that use style-linking, when selecting the Regular weight, if you click the "Bold" style, the Bold weight will be used. This is mentioned in the ReadMe file.
