### ISSUE TITLE
Mismapping of 具

### ISSUE THREAD

**Issue by pan-asian-wok** [adobe-fonts/source-han-serif#120]
Apologies for flooding the Issues section with yet another incorrect mapping report. I noticed that Source Han Serif 2.0's 具 in the Taiwan and Hong Kong versions is the same as the Japanese one, which is incorrect. Please refer to the example below of how 具 was before version 2.0.

When quickly looking through other characters with the component 具, I did not notice any other incorrect mappings.

![Mismapping of 具](https://user-images.githubusercontent.com/45274474/139383321-b3cc63f2-a4b5-472d-bde2-35a35e640fec.JPG)

**Comment by punchcutter** [comment]
Fixed. This happened because the old CN glyph was removed since it's almost completely identical to uni5177uE0101-JP.

**Comment by punchcutter** [comment]
Fixed in 2.001
