### ISSUE TITLE
Incorrect mappings of 角，歸

### ISSUE THREAD

**Issue by gbnewb** [adobe-fonts/source-han-serif#122]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

![image](https://user-images.githubusercontent.com/88551948/139464612-3d660f1d-99df-41eb-8e89-e2048a7b2e7a.png)

Every character with 角，歸 and within CNS 11643 Planes 1 & 2 should be checked in order to complete fix the problem. I didn't check them all. Interestingly, for some unknown reason, a few characters like 掃 and 婦 are not mapped wrong.

**Comment by punchcutter** [comment]
Fixed in 2.001.
