### ISSUE TITLE
Wrong mappings for U+2E569 U+E0100 and U+884B

### ISSUE THREAD

**Issue by trueroad** [adobe-fonts/source-han-serif#126]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description
![source-han-serif-2 000-wrong-mapping](https://user-images.githubusercontent.com/3464255/139578505-a2deccfd-b97f-4a46-8974-fb382653a0a2.png)

If I understand correctly, SourceHanSerif version 2.000 has wrong mappings for U+2E569 U+E0100 and U+884B.

U+2E569 U+E0100 is a completely different letter from U+2E569.
I would like U+2E569 U+E0100 to be the same glyph as U+2E569.

U+884B is the same glyph as U+884B U+E0101 instead of U+884B U+E0100.
I would like U+884B to be the same glyph as U+884B U+E0100 instead of U+884B U+E0101.

**Comment by punchcutter** [comment]
U+2E569 U+E0100 must have had a copy/paste error and got the CID from the previous line in the IVS file. Fixed now. 

The mappings for U+884B are currently the same as in Source Han Sans, but that's also a mistake that needs to be corrected there. Fixed in Serif now.

**Comment by punchcutter** [comment]
Fixed in 2.001.
