### ISSUE TITLE
Glyph 啟(U+555f) and 啓(U+5553) with wrong mapping in TC version.

### ISSUE THREAD

**Issue by ButTaiwan** [adobe-fonts/source-han-serif#13]
Glyph 啟(U+555f) and 啓(U+5553) with wrong mapping in Traditional Chinese version.

In MOE standard, 戶 part should be started with 撇 (left-falling stroke), not 點 (dot).
Source Han Serif TC map to the SC ones, but they was correct in Source Han Sans.
It's good to mapping to Korean style ones.

![image](https://cloud.githubusercontent.com/assets/5418570/24691681/9c56f5da-1a07-11e7-98df-1ad699b56516.png)

**Comment by kenlunde** [comment]
Thank you. This will be fixed by mapping U+5553 and U+555F to _uni5553uE0101-JP_ and _uni555F-JP_, respectively, in the TW CMap resource.

**Comment by kenlunde** [comment]
Consolidated with Issue #27.
