### ISSUE TITLE
Misfollowing of Taiwan MOE 䒑

### ISSUE THREAD

**Issue by NightFurySL2001** [adobe-fonts/source-han-serif#133]
Source Han Serif does not meet the requirement of two dots in 立, 豆, 辛, 幸 to be connected to the top and bottom stroke for TW and HK as per written requirement in Taiwan's 國字標準字體教師手冊. New glyphs will be required for all involved characters (or adjustments be made).

Are there any consideration involved in why is this so?

立: https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/STD/p173.htm?open
![image](https://user-images.githubusercontent.com/33471049/138229821-21e8b746-798f-40bc-a5ae-9759fefb182a.png)

豆: https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/STD/p203.htm?open
![image](https://user-images.githubusercontent.com/33471049/138229679-09458747-7b17-4a33-aade-f770897ef473.png)

辛: https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/STD/p212.htm?open
![image](https://user-images.githubusercontent.com/33471049/142585018-697a0371-863a-4611-b1c6-d503b1eb83e1.png)

幸: https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/STD/p117.htm?open
![image](https://user-images.githubusercontent.com/33471049/142585082-8b321681-0e41-4f1f-977d-014ad968eca8.png)

List of involved characters in Big-5 (287 characters):
位倍傽僮儭剖唼啦嚫垃培墇墥妾婄嫜岦嶂幛幢彰慞憧戇拉掊接撞敨新昱暲曈朣柆棓椄樟橦櫬殕毅毰氃泣涪湇漳潼瀙灨焙煜熤犝獐獞琣璋瓿瘴瞕瞳砬碚穜立竑竘站章竣竤童竦竫竭竮端競竷笠篰粒罿翊翋翌翣膧艟苙菈菨菩蒞蒟蓓蔀蕫薪藙藽蟑襯親賠贛踣踥遧部鄣醅鐘陪障霎霠靖鞡颯騿鯜鱆鴗鷑偣億喑噫噷噾堷境嬂幟意愔憶戠摬摿暗樈樴檍歆湆澺熾燱獍瘖窨竟織繶職腤膱臆萻薏蘵蟙諳識醷鏡鐿闇音韶韸韹韺韻韽韾響頀鷾黯僻劈厗垶壁嫴嬖孽宰屖峷嶭巕幦廦憵擗擘梓橭檗櫱滓澼璧瓣甓癖礔糪糱縡繴臂莘薛薜蘗蠥襞謘譬躄躠辛辜辣辦辨辭辮辯避鋅闢霹騂鷿鼊倖啈圉圛執報墊墿婞嶧悻慹懌摯擇斁檡涬澤燡瓡盩盭睪睾籜縶繹蓻蕔蘀蟄蠌襗謺譯贄醳釋鐸騺驛鷙鸅

![image](https://user-images.githubusercontent.com/33471049/142585349-8e2bf0f5-def7-433c-a2ac-7edf9004a53c.png)

**Comment by hfhchan** [comment]
If you follow the quoted document 國字標準字體教師手冊 closely then the first stroke of the 貝 needs to touch the top of 目 as well. That would lead to an insurmountable amount of glyphs. Also the mentioned glyph forms are not popular in commercial fonts developed by Taiwanese vendors either.

**Comment by punchcutter** [comment]
Source Han does not claim to follow Taiwan MOE strictly. There are notes in the ReadMe PDFs for both Sans and Serif. Under **Glyph Set Particulars** it says "the glyphs may or may not adhere to the Taiwan MOE glyph standard" and under **Language Particulars** "the glyphs mostly adhere to the Taiwan MOE (Ministry of Education) glyph standard". As @hfhchan stated above one reason not to strictly follow every possible rule in every possible standard is that we are already limited in how many glyphs we can support in a single font.

**Comment by NightFurySL2001** [comment]
I would suggest removing unofficial CN 辶 difference in favour of written requirement of 䒑 in TW since the priorities are different.
