### ISSUE TITLE
HK & TW glyph issue for U+50F0 僰 and U+68D7 棗

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#135]
Source Han Serif Version: v2.000

![u50F0,u68D7](https://user-images.githubusercontent.com/959433/142711392-bc7bc851-b378-4b8b-84fd-d2f05e5b7ffa.png)

This one is easy to get overlooked. I just spot this by accident.

The CN glyphs for U+50F0 僰 and U+68D7 棗 cannot be used for HK or TW because of the difference in the 朿 component.
For U+68D7 棗, suggest to remap TW and HK to JP.
For U+50F0 僰, unfortunately (?) the JP glyph cannot be directly used because of the stroke form difference in the last stroke of 朿 on the right.
If allocating a new glyph isn't possible right now, I think the JP glyph is preferable for this case.

**Comment by Marcus98T** [comment]
While this isn't related to the HK/TW mapping issue, I also want to point out the KR mapping for U+68D7 棗 should be the same as the JP version. Please fix this as well.

While some major Korean fonts like (from left to right) Adobe Gothic Std, Apple Myungjo Std, Apple SD Gothic Neo and Apple Gothic have the CN form, this I think is inconsistent. Apple Myungjo (far right) has the JP form.

<img width="358" alt="Screenshot 2021-12-06 at 16 17 03" src="https://user-images.githubusercontent.com/10541683/144811310-ee9591d0-78f7-40ec-a65d-3de3432d7da7.png">

While yes, the Korean Unicode reference is not consistent in some ways, I think 棗 needs to be more consistent with the other glyphs that have 朿 as the component.

<img width="939" alt="Screenshot 2021-12-06 at 16 10 18" src="https://user-images.githubusercontent.com/10541683/144810951-7fdbae5c-9aa3-4450-a44c-4b139c3be69a.png">
<img width="927" alt="Screenshot 2021-12-06 at 16 10 54" src="https://user-images.githubusercontent.com/10541683/144810966-703ed378-aa4a-41bb-bcb3-814c201e135d.png">
<img width="800" alt="Screenshot 2021-12-06 at 16 11 14" src="https://user-images.githubusercontent.com/10541683/144810972-23401fd1-c5fb-46cd-b1d6-56e09886048c.png">

**Comment by tamcy** [comment]
Fix to U+68D7 and U+50F0 confirmed in v2.001. Thanks!

**Comment by NightFurySL2001** [comment]
![image](https://user-images.githubusercontent.com/33471049/165059329-4b5860c3-2eb3-400b-a0ae-7276ee8e350c.png)
@punchcutter Inconsistent record in Readme file compared to here.

**Comment by punchcutter** [comment]
Removed the mistaken line from the README.
