### ISSUE TITLE
HK & TW glyph issue for U+9ED5 黕 and U+9EE0 黠

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#136]
Version: 2.000

![u9ED5,u9EE0](https://user-images.githubusercontent.com/959433/142712151-9f7acd63-5798-4a21-85c2-9f5c36624c06.png)

The circled region indicates a stroke type difference between CN and HK/TW. 
For U+9ED5 黕, the JP glyph could be used.
For U+9EE0 黠, a new glyph would be needed.

**Comment by punchcutter** [comment]
There is already a TW glyph for U+9EE0 that has been restored. There is also a TW glyph for U+9ED5, but it's not that much different from the JP which is why it was dropped.
<img width="538" alt="9ED5-TW-JP" src="https://user-images.githubusercontent.com/11257204/142806760-c17e6c0b-0981-49aa-a879-b1abdd213711.png">
Here is TW on left and JP on right. I feel like the TW glyph looks better overall.

**Comment by tamcy** [comment]
As I am not a typeface designer I am not in a good position to comment on this, but also I agree that the TW glyph looks better, mainly because of the placement of the four dots 灬. But it would still be fine to use the current JP glyph if the designer doesn't agree to replace it with the TW one. I say this because the stroke above that 灬 isn't consistent in JP, and it seems to me that the JP glyph designer tends to preserve the same flow of the four dots (灬) no matter which stroke type is used above that 灬:

![jp](https://user-images.githubusercontent.com/959433/142816863-9f520d2c-31a1-41f6-9333-c0d80dc6f8fb.png)

And it doesn't seem to worth allocating a new CID just for this difference 😄.

**Comment by punchcutter** [comment]
Definitely not saying we should add both the TW and JP. Just using one is fine. Easiest right now is to map TW/HK to the existing JP.

**Comment by Marcus98T** [comment]
Sorry if I commented quite late, but I kinda felt the CN glyph for 黕 should have been the JP glyph, but adjust that 冘 such that the last stroke is closer to the other "JP" glyph, then afterwards can remap to JP, KR and CN.
<img width="297" alt="Screenshot 2021-12-07 at 01 24 54" src="https://user-images.githubusercontent.com/10541683/144892686-000d40cf-801b-4993-bcd2-4ce39a86abc5.png">

Then either no need to restore the TW and map that current "JP" to TW/HK, or restore the other TW form and drop the old "JP" glyph.

**Comment by tamcy** [comment]
Fix to U+9ED5 黕 and U+9EE0 黠 confirmed in v2.001 release, thanks!

**Comment by tamcy** [comment]
I am closing this as @Marcus98T has his own issue about this in #148.
