### ISSUE TITLE
U+58A8

### ISSUE THREAD

**Issue by CuervoCarlos** [adobe-fonts/source-han-serif#139]
### Prerequisites

* [y] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [y] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [y] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

Character: 墨
Unicode: U+58A8

![58A8 issue](https://user-images.githubusercontent.com/95687225/145017341-63a31cd1-33a4-43a0-a3bd-9f2ffeaefcf6.png)

Attached above is a comparison between Source Han Sans and Serif, note characters in red, the CN and TW glyphs should follow the KR suit.

**Comment by punchcutter** [comment]
Thanks, that mapping got lost in the update because it's actually mapped to uniFA3A-JP and the corresponding mapping file didn't get updated. Already fixed for the next update.

**Comment by punchcutter** [comment]
Fixed in 2.001
