### ISSUE TITLE
Glyph issue concerning 化 (U+5316) for CN.

### ISSUE THREAD

**Issue by celestialphineas** [adobe-fonts/source-han-serif#14]
The longer left-falling stroke (撇) of 化 (U+5316) looks uncomfortable for users with Simplified Chinese background.

## Problem with the crossing of the right component

The center seems too high.

![issue1](https://cloud.githubusercontent.com/assets/17267055/24692426/7313fd40-1a0b-11e7-9ce6-a611f91741d8.PNG)

And the extended part of the stroke is a bit too short.

![issue2](https://cloud.githubusercontent.com/assets/17267055/24692772/29afb78c-1a0d-11e7-938a-b1b76203e0fd.png)

The extended part from the cross is almost invisible in smaller font size. That makes the glyph looks strange and may confuse a user with Simplified Chinese background as a typo. It would probably result in low legibility of this common glyph. And I have to say that it should not be considered as a feature, but an error. Even for typefaces known for its wide counter (like FounderType Boya Song as shown above), the extended 撇 is much more visible.

## In other glyphs

花 (U+82B1) meets the same problem, however 讹 (U+8BB9) and 华 (U+534E) look fine, causing inconformity of the component.

![issue3](https://cloud.githubusercontent.com/assets/17267055/24693678/4f2b57c4-1a11-11e7-92a7-0b105143aafd.png)

**Comment by kenlunde** [comment]
Thank you. I will ask our designer to confirm and to modify _uni5316uE0101-JP_ and _uni82B1uE0101-JP_, which are shared by the CN and KR CMap resources. The JP and TW CMap resources use different glyphs for these two characters: _uni5316-JP_, _uni5316-TW_, _uni82B1-JP_, and _uni82B1-TW_.

**Comment by kenlunde** [comment]
Consolidated with Issue #27.

**Comment by celestialphineas** [comment]
More about issue 14. The component 化 (U+5316) lack consistency.
![issue4](https://cloud.githubusercontent.com/assets/17267055/24937590/4f5e4bd6-1f64-11e7-92f3-927ab154bd67.PNG)

**Comment by kenlunde** [comment]
Here is an additional rendering of these characters, showing how each one shows in each language-specific font. The order of the lines is Simplified Chinese, Traditional Chinese, Japanese, and Korean. Orange signifies a JP glyph variant, green signifies a CN glyph, orange signifies a TW glyph, and red signifies a JP glyph. Here are the actual characters:

U+5316 化, U+534E 华, U+542A 吪, U+56EE 囮, U+6779 杹, U+6C8E 沎, U+709B 炛, U+82B1 花, U+8A1B 訛, U+8BB9 讹, U+8CA8 貨, U+8D27 货, U+920B 鈋, U+9B64 魤

![component-example](https://cloud.githubusercontent.com/assets/3988788/24973897/4ebf51a0-1f75-11e7-985f-bdf988acc390.jpg)
