### ISSUE TITLE
Wrong glyph for 墨 of Simplified Chinese

### ISSUE THREAD

**Issue by PomponOnion** [adobe-fonts/source-han-serif#144]
<img width="600" alt="Compare 1" src="https://user-images.githubusercontent.com/96934392/147845064-f4121df9-b9b6-44f2-9e76-99a80f3cb09a.png">

![Compare 2](https://user-images.githubusercontent.com/96934392/147845084-fef88a3d-5ab7-40de-b5e4-7d1a3ca272ac.jpg)

**Comment by punchcutter** [comment]
Duplicate of https://github.com/adobe-fonts/source-han-serif/issues/139
