### ISSUE TITLE
Slight misalignment for countour in some characters

### ISSUE THREAD

**Issue by NightFurySL2001** [adobe-fonts/source-han-serif#146]
There is a slight misalignment for these characters:

䮺 (U+4BBA), 刀 component, in CN Extralight
![image](https://user-images.githubusercontent.com/33471049/148149996-5ef6fa20-8538-41be-8e0e-df1f5ce6a8a7.png)

㊜ (U+329C), 辶 component, in CN Extralight
![image](https://user-images.githubusercontent.com/33471049/148150106-55b6818e-57d6-4553-be13-4f5d01e677d2.png)

**Comment by punchcutter** [comment]
Thanks. Fixed for next update.

**Comment by punchcutter** [comment]
Fixed in 2.001.
