### ISSUE TITLE
Wrong glyph 壯(U+58EF) in JP and KR

### ISSUE THREAD

**Issue by Huanying04** [adobe-fonts/source-han-serif#149]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description
![缺壯字](https://user-images.githubusercontent.com/59917505/149459817-8d0f1620-6d1d-4d4d-9e19-a9d2f3861c3e.png)

In the above image, the left side is the older source han serif which has correct glyph of 壯, same as the glyph in the JIS standard in the following image. But in version 2.000R, the right side, there's just TW/CN/HK standard 壯.

![壯](https://user-images.githubusercontent.com/59917505/149459822-842fa121-4c5e-4f9b-88b5-fc27b65fca5c.PNG)

**Comment by punchcutter** [comment]
Fixed in 2.001
