### ISSUE TITLE
SuperOTC folder missing from release branch (plus its download link in README.md returns Not Found error)

### ISSUE THREAD

**Issue by SilSinn9801** [adobe-fonts/source-han-serif#151]
### Prerequisites

* [ ] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [X] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [X] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

The **SuperOTC** folder, which was present in the release branch (https://github.com/adobe-fonts/source-han-serif/tree/release), is now missing there. Also the download link for the static **Super OTC** (https://github.com/adobe-fonts/source-han-serif/releases/download/2.000/SourceHanSerif.ttc.zip) stated in README.md returns a `Not Found` error message. For now, the only way to download it is from the Releases page (https://github.com/adobe-fonts/source-han-serif/releases/tag/2.000R) by clicking on the **Static Super OTC** asset link.

**Comment by punchcutter** [comment]
The SuperOTC folder was removed because the file has become too large to store without LFS and we aren't going to use that just for this purpose. The links in the README have been fixed now.
