### ISSUE TITLE
Release-branch ZIP download is larger than 2 GiB, gets truncated when downloading over HTTPS; Part 1 download at Releases page also larger than 2 GiB

### ISSUE THREAD

**Issue by SilSinn9801** [adobe-fonts/source-han-serif#152]
### Prerequisites

* [ ] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [X] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [X] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

The full Release branch has grown too big with the inclusion of Variable fonts. Just like what happened at the sister project Source Han Sans last April (see https://github.com/adobe-fonts/source-han-sans/issues/294), the ZIP download over HTTPS for **release** branch gets truncated at almost 2 GiB, resulting in the Variable folder partially missing. The same thing happens to the **Part 1** download link at https://github.com/adobe-fonts/source-han-serif/releases/tag/2.000R which I suspect is the same full Release-branch archive rather than a subset of it. The problem at Source Han Sans was solved by creating a `.gitattributes` file at the root folder with the following contents:
```
# Ignore files when creating a Release so we can control how we attach the assets
.gitattributes export-ignore
# exclude the Variable folder for releases and attach a zip to keep the default release zip smaller
Variable export-ignore

# Tell GitHub not to categorize these files as language files
**/*.SC linguist-vendored
**/*.HC linguist-vendored
**/*.J linguist-vendored
```
I propose that the same thing be done for Source Han Serif here to control the size of the ZIP download over HTTPS as well as the size of Part 1 in Releases.

**Comment by punchcutter** [comment]
There is already a `.gitattributes` for this reason. For 2.000 I didn't update that file first so the release zip archive is too large, but to fix it would mean deleting the whole release and I didn't want to do that while people were already downloading so I left it alone. 2.001 will work as expected.
