### ISSUE TITLE
Mapping error in CN for U+5141 (允) and U+535A (博)

### ISSUE THREAD

**Issue by NightFurySL2001** [adobe-fonts/source-han-serif#162]
Affects 允 and 博.
![image](https://user-images.githubusercontent.com/33471049/167236642-af27b25c-a0ea-40ca-bbdc-d69b69958480.png)

**Comment by Pal3love** [comment]
To provide more context, the affected characters are **uni5141 (允) and uni535A (博)**, which have different shapes in SC/TC/HC vs J/K.

Expected mappings should be:
uni5141 (允) | cid10832 -> J & K, cid10833 -> **SC** & TC & HC
uni535A (博) | cid11682 -> J & K, cid11683 -> **SC** & TC & HC

Current mappings in SHSerif 2.001, which needs to fix, are:
uni5141 (允) | cid10832 -> J & K & **SC**, cid10833 -> TC & HC
uni535A (博) | cid11682 -> J & K & **SC**, cid11683 -> TC & HC

Expected 允博 for SC/TC/HC:
![Expected 允博 for SC/TC/HC](https://user-images.githubusercontent.com/8181271/168495498-37be472d-970a-4e61-8a34-5351612dc17f.png)

Expected 允博 for J/K:
![Expected 允博 for J/K](https://user-images.githubusercontent.com/8181271/168495760-6b786d0d-24f7-4251-8aac-b4ccf067d3eb.png)

If possible, please prioritize this issue as both characters are daily used in Chinese, such as 允许 (allow), 博士 (doctor).

Thanks!

**Comment by NightFurySL2001** [comment]
U+535A (博) for CN should be mapped to CID+62034 as the 甫 does not have a hook. Also, the mentioned mapping is incorrect for KR.

Current mapping:

CID+11682 - JP, *CN*
CID+11683 - TW, HK
CID+62034 - KR, JP U+E0101

Revised mapping:

CID+11682 - JP
CID+11683 - TW, HK
CID+62034 - KR, JP U+E0101, *CN*



获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by punchcutter** [comment]
Fixed mapping for next release

**Comment by Marcus98T** [comment]
Fix verified in Noto Serif v2.002. CN is using the TW glyph for 允 (U+5141) and the KR glyph (uni535AuE0101-JP) for 博 (U+535A). I think this is good enough.

<img width="238" alt="Screenshot 2023-08-17 at 20 29 23" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/b7893cbc-ca84-47b8-828c-133a8ceb4771">

**Comment by NightFurySL2001** [comment]
Verified fix in v2.002.
