### ISSUE TITLE
No mention of U+32FF in changelog

### ISSUE THREAD

**Issue by lionslancer** [adobe-fonts/source-han-serif#163]
### Prerequisites

* [X] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [X] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [X] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

U+32FF (㋿ Square Era Name Reiwa) was added to Source Han Sans with the release of version 2.001 in 2019, but was unavailable in Source Han Serif for some time, as the next release was in 2021. U+32FF was made available in Source Han Serif version 2.000, but there is no mention of it in the changelog. I simply wanted to bring attention to this, in case it was an accidental omission.

**Comment by punchcutter** [comment]
Thanks for pointing it out. Somehow that got skipped in the release notes, but I'll update it for the next release.
