### ISSUE TITLE
Mismapping of U+F9DC (隆)

### ISSUE THREAD

**Issue by 4b3** [adobe-fonts/source-han-serif#165]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

Compatibility Ideograph U+F9DC (隆) is mapped to CID+43068 (⿰阝⿱夂生) in all regions in v2.001.
It should be mapped to CID+43069 (⿰阝⿳夂一生).

U+F9DC is sourced from J3-7D5D and K0-6B58.
J3-7D5D is the traditional form for the JP form of U+9686 (隆).
K0-6B58 is a heteronym of U+9686.
Both are identical to the CN, HK, TW, and KR forms of U+9686 (=CID+43069).

Note that <9686 FE00>, the SVS corresponding to U+F9DC, is correctly mapped to CID+43069.

**Comment by punchcutter** [comment]
Fixed in https://github.com/adobe-fonts/source-han-serif/releases/tag/2.002R
