### ISSUE TITLE
Inconsistent 父 for 爹 in TW/HK Versions of Source Han Serif

### ISSUE THREAD

**Issue by pan-asian-wok** [adobe-fonts/source-han-serif#167]
Hello,

I noticed that the form for 父 is inconsistent for 爹 compared to other words that have 父 in them. I have attached some examples.

![父](https://user-images.githubusercontent.com/45274474/183818702-6b487646-4d60-4924-8de7-8183540719bd.jpg)

**Comment by punchcutter** [comment]
Looks like this mistake happened because TW in Sans is mapped to JP, but it shouldn't be here so it's updated now.

**Comment by NightFurySL2001** [comment]
In Sans, TW is mapped to JP due to connected 夕. In Serif, TW can be mapped to CN as this different does not appear anymore. However, the 多 component might need to be adjusted to slightly match JP stability.

**Comment by Marcus98T** [comment]
Fix verified in Noto Serif v2.002; TW and HK are using the CN glyph. But Adobe can't be bothered to adjust the 多 component in the CN glyph as they deem it unimportant. Hopefully this design issue will not be ignored in the next release.

<img width="164" alt="Screenshot 2023-08-17 at 20 46 58" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/caba1d2d-7530-476c-b903-010a7a117dad">
