### ISSUE TITLE
Misunification of U+5CB8 (岸)

### ISSUE THREAD

**Issue by 4b3** [adobe-fonts/source-han-serif#169]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

U+5CB8 (岸) should be separated into JP/KR and CN/TW/HK forms by the shape of the break in the second stroke of 山.
The five letters shown here as an example, 岩, 岳, 岸, 島, and 崩, are screenshots from region-map.xlsx v2.001, and all meet the criteria for inclusion in the subset of five regions, but only 岸 is unified.

<img width="759" alt="region-map-radical-mountain" src="https://user-images.githubusercontent.com/4629752/189471262-cee332dc-2de3-49a6-925d-b2743969a309.png">

**Comment by punchcutter** [comment]
The JP glyph was mistakenly removed with all the big changes for 2.000 update. It will be back in the next update.

**Comment by punchcutter** [comment]
Fixed in https://github.com/adobe-fonts/source-han-serif/releases/tag/2.002R
