### ISSUE TITLE
Can not show "Latin small letter g with circumflex(ĝ)" in InDesign

### ISSUE THREAD

**Issue by WildDagger** [adobe-fonts/source-han-serif#172]
I'm using han-serif in InDesign and my content has Esperanto glyph (like "ĝ")
However, I can not show this glyph in InDesign whatever I use composite fonts it still can not show and notice that "Glyph Lost".
I installed all font in Zip File from Latest Version of Official Site so what's going on?
It's so annoying...

![image](https://user-images.githubusercontent.com/17616055/217132950-e663b473-b09b-4225-b063-9dd23d29d1e4.png)
Just like that, the Top is han-serif, the Middle is Times New Roman and the Bottom is Segoe UI.

**Comment by punchcutter** [comment]
That glyph is not in Source Han Serif. If you are using composite fonts then you need to make sure the font you want to use has that glyph. It also won't show up if you only choose a different font for "Roman" letters so you need to add a custom set to the composite font and add letters like ĝ to that set. Then it will work.
