### ISSUE TITLE
書 (U+66F8) should use uni66F8uE0101-JP for HK

### ISSUE THREAD

**Issue by Marcus98T** [adobe-fonts/source-han-serif#175]
Applies to both Sans and Serif. I don't know why they made one extra similar glyph for HK when there is already a JP variant glyph that should suit HK. Therefore, I suggest the current HK glyph be removed and the JP variant glyph be mapped to it instead.

Left (Red) - HK glyph; Right (Blue) - JP variant glyph uni66F8uE0101-JP
<img width="294" alt="Screenshot 2023-02-21 at 02 19 28" src="https://user-images.githubusercontent.com/10541683/220177091-6c2f7551-4340-46e7-a054-41383d162520.png">

Here's a comparison. They are not 100% identical, although the difference is not too obvious for Sans. Same colours, overlaid on top of each other.
![書_Sans](https://user-images.githubusercontent.com/10541683/220177174-e6f791cf-78bb-441d-9dbd-0e63c25a9cd3.png)
![書_Serif](https://user-images.githubusercontent.com/10541683/220177177-7b0499e3-7be3-4085-88b7-4c00cd6cd69d.png)

For Sans, the CID for the current HK glyph is 20661 and the CID for the JP variant glyph is 62380.
<img width="366" alt="Screenshot 2023-02-21 at 02 26 47" src="https://user-images.githubusercontent.com/10541683/220178139-83f7b44b-d4ab-4332-a48a-407cfb050d05.png">
<img width="227" alt="Screenshot 2023-02-21 at 02 27 23" src="https://user-images.githubusercontent.com/10541683/220178146-f9ae6691-2cfc-4a3a-9b59-2ef68108e7fa.png">

For Serif, the CID for the current HK glyph is 20616 and the CID for the JP variant glyph is 62270.
<img width="393" alt="Screenshot 2023-02-21 at 02 23 04" src="https://user-images.githubusercontent.com/10541683/220178180-0e43d64a-ac5f-4a25-be99-ccb85e729781.png">
<img width="226" alt="Screenshot 2023-02-21 at 02 24 42" src="https://user-images.githubusercontent.com/10541683/220178190-88ee45ab-b9a9-4411-908c-dc531b7974c9.png">

**Comment by Marcus98T** [comment]
Uh, this is not fixed in Noto Serif v2.002 and is made worse. HK is using uni66F8-JP, not uni66F8uE0101-JP. Please fix this.

<img width="162" alt="Screenshot 2023-08-17 at 20 04 09" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/bc6cac61-e1be-42f3-81b8-360193495423">

**Comment by CoolMarvel43** [comment]
Fix verified. This issue is considered resolved.

<img width="652" alt="Screenshot 2024-07-31 at 22 50 00" src="https://github.com/user-attachments/assets/651482a3-a799-4790-907a-077e8448157a">
<img width="354" alt="Screenshot 2024-07-31 at 22 50 10" src="https://github.com/user-attachments/assets/8a862e47-88f6-41c6-9be0-01fce1b00642">
