### ISSUE TITLE
Traditional-orthography (Kangxi-isque) version

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#19]
A version of Source Han Serif using the traditional orthography would be great.

Currently, the orthography of the Korean region is the most conservative and fits into the traditional orthography commonly seen in books printed in Hong Kong and Taiwan today and also in China before the 1970s.  However, the number of characters in the Korean version are severely limited that it is not usable for daily typesetting for Traditional Chinese users who wish to use traditional orthography.

Traditional-orthgraphy is also preferred for specific Japanese use, notably in place names and personal names.  Tradtional-orthography stands as the lowest common denominator for truly pan-CJK use.

A large amount of glyphs needed could be repurposed from the Korean or Japanese version.

Since Adobe has the original tools to programmatically generate outlines from strokes, it is much easier for Adobe to maintain such a version than for the community to maintain a fork using the munged outlines.  A traditional-orthography based font could serve useful purposes for standardization in Unicode Code Charts as the lowest common denominator too.

**Comment by kenlunde** [comment]
This is being labeled DIY, for the same reasons why the comparable issue was labeled in the same way for _Source Han Sans_. We are not able, at least at this time, to provide the glyphs in a form that would make this an easier task, though it has been under consideration.

**Comment by kevite** [comment]
@hfhchan It seems the non region-specific versions and OTCs cover characters used in Chinese. I haven't noticed any problems using the OTC.
https://www.google.com/get/noto/help/cjk/
Characters unused in Chinese and even some simplified characters were Kangxified for the Korean version:
https://www.facebook.com/groups/inheritedglyph/permalink/1519227208119879/?comment_id=1519494138093186&comment_tracking=%7B%22tn%22%3A%22R6%22%7D

**Comment by KrasnayaPloshchad** [comment]
As a solution, you can try this derivative works.
https://github.com/ButTaiwan/genyo-font
