### ISSUE TITLE
Win10 recognizes as two different fonts when using different system non-Unicode language settings

### ISSUE THREAD

**Issue by Enix-Xu** [adobe-fonts/source-han-serif#192]
Hello, can anyone help advice?
We are experiencing issues with the Source Hans Serif font: 
When used on a Simple Chinese Win 10 system, the font appears as "思源宋体 CN" whereas on an English system it appears as "Source Hans Serif CN". 
Microsoft Office recognizes these as two separate fonts not same font, which could cause font errors when sharing files between simple Chinese and English systems.  I guess in Chinese system ,"Source Hans Serif CN" will be recognized as some Japenses Font.(see bottom image)
I checked there's no such issue on system default font. 
Other font will be:  
#1 No matter simple Chinese or English, font name show as English name,
Or #2 even show as Chinese font name in Chinese system, there's no such issue.

![image](https://github.com/adobe-fonts/source-han-serif/assets/141305338/e1aec41a-5d3d-4b31-9154-719eab929f33)
![image](https://github.com/adobe-fonts/source-han-serif/assets/141305338/fea0aa15-7c5b-4fff-ad70-bcabb3f3e9ce)
![image](https://github.com/adobe-fonts/source-han-serif/assets/141305338/6a70036f-8627-44c4-bf36-8b2befc2ccd6)

**Comment by NightFurySL2001** [comment]
This is an issue with Microsoft Office and not a problem with the font file itself. There is a localised font name in the font file which will display Chinese (Simplified) name in Chinese (Simplified) system, and English system with Chinese (Simplified) language pack installed under Settings - Time & Language - Language (unverified extent but that's how it worked on my system). 

If installing the language pack in Settings doesn't work, I can suggest some methods:
1. use [Noto Serif SC](https://github.com/notofonts/noto-cjk/) (under Serif/SubsetOTF) released by Google. It is equivalent to Source Han Serif CN but does not have localised name so you won't encounter this problem.
2. manually remove the localised name in the Source Han Serif font file (e.g. [ttx](https://fonttools.readthedocs.io/en/latest/ttx.html)).
3. add a registry entry that alias the Chinese/English name to the other.  
> **Warning**
> Modifying the registry improperly can result in Windows becoming corrupted. You should only attempt these directions if you have your data backed up and are willing to risk creating additional problems.

Go to `\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes`. Add a string value, name it as the font name not on your system (e.g. `思源宋体 CN`). Double click the entry and fill in the font name that is present on your system (e.g. `Source Hans Serif CN`). Relog and fonts using both name will show up properly, but you can't set the font with names that are missing in the system (it's just adding a fallback link, not installing a new font).
