### ISSUE TITLE
[v2.002] Some minor issues with the font

### ISSUE THREAD

**Issue by Marcus98T** [adobe-fonts/source-han-serif#195]
Well @punchcutter is kindly asking me to keep all the issues organised into one place, so I'll just repost here. I was rushing to report issues when I simply do not understand how the development process and schedule between Noto CJK and Source Han is like.

At the time of writing these issues, Noto Serif CJK v2.002 was released a day before Source Han Serif, which was why I prematurely posted them there. Now that Source Han Serif v2.002 has been released, I should have just kept my issues here. I need to learn some patience and don't expect everything to go my way.

Anyway, here are the early issues I found with this font:

## uni9FEE-JP (鿮) is using an inappropriate CN Song-style decoration in the top part of the 帯 component

_Original closed issue: https://github.com/notofonts/noto-cjk/issues/254_

I have a design issue with uni9FEE-JP (鿮). This CN Song-style decoration as circled in red is inappropriate for Japanese traditional print orthography. I think Arphic designed this, when they are normally responsible for designing Chinese glyphs only, not Japanese. Anyway, please follow the reference of 帯 (U+5E2F, circled in green) and fix this glyph.

<img alt="Screenshot 2023-08-17 at 21 00 28" width="230" src="https://user-images.githubusercontent.com/10541683/261316080-48a4ea0e-e399-487a-b7ed-3bb467690f56.png">

Also maybe fix the bottom part of 帯 by separating the 巾 component from the 冖 component.

## [Release Notes Only] Duplicate mention of the TW/HK 全 mappings in the v2.002 release notes

_Original closed issue: https://github.com/notofonts/noto-cjk/issues/255_

I have a minor issue in the [release notes for Noto CJK Serif v2.002](https://github.com/notofonts/noto-cjk/blob/main/Serif/NEWS.md#noto-serif-cjk-release-notes) regarding this line:

> * Fixed TW/HK mappings for U+5168 全, U+6D24 洤, U+8DE7 跧, U+8F07 輇, and U+9293 銓 per [Issue #109](https://github.com/adobe-fonts/source-han-serif/issues/109).

This was already fixed in v2.001, so there's no need to mention this line in v2.002. Probably it's here due to human error.

**UPDATE:** [Also applies to the main branch.](https://github.com/adobe-fonts/source-han-serif/blob/422e1ad801c8bcd2257941c9d47863ddfa29b21c/SourceHanSerifReadMe.pdf)

<img width="931" alt="Screenshot 2023-08-18 at 17 20 28" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/9e458043-e189-4d8e-ac96-a3526b484935">

<img width="685" alt="Screenshot 2023-08-18 at 17 29 02" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/e1a1f69f-4bf2-407b-9eff-8eaf87b57361">

## Wrong HK mapping for 書 (U+66F8)

[I mentioned this before](https://github.com/adobe-fonts/source-han-serif/issues/175#issuecomment-1682166661), but anyway, I'll repost it here for organisational purposes.

I don't know what's going on here, but I think the HK glyph got remapped to the regular JP glyph of uni66F8-JP, not the _JP variant glyph of uni66F8uE0101-JP_ as I requested. Please fix the mapping, but **do not revert back to uni66F8-HK**, as that glyph should be orphaned and removed in the next major version of Serif.

<img width="162" alt="Screenshot 2023-08-17 at 20 04 09" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/bc6cac61-e1be-42f3-81b8-360193495423">
<br>
<img width="172" alt="Screenshot 2023-08-18 at 15 58 02" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/d1192b5e-aa26-4e94-884e-c0f74c2d2346">

---

This project seems to not get the attention it deserves nowadays, without Ken Lunde, who again, was the only person to at least inform us of any changes and fixes beforehand. There are so many issues left unsolved.

At least if Adobe decides not to address them, they should say so and close them as not planned, not keep it open forever. After this release, they need to look through every single issue that's still open again. We need better communication regarding this.

**Comment by Marcus98T** [comment]
Regarding uni9FEE-JP (鿮) there is another minor problem. While the glyph is interpolatable, there's a double node as circled (marked in red in the Glyphs app), which means there are two points on the exact same coordinates. Maybe in the next update, this double node needs to be resolved.

<img width="524" alt="Screenshot 2023-09-02 at 18 25 00" src="https://github.com/adobe-fonts/source-han-serif/assets/10541683/20e3b52f-3a6d-42e2-955a-da381ae55478">

**Comment by tamcy** [comment]
@Marcus98T The component was designed this way to prevent overshoot for overlapped strokes during interpolation. All glyphs with the same component will exhibit the same behavior.

![Untitled](https://github.com/adobe-fonts/source-han-serif/assets/959433/18e7b869-8370-43df-96e3-4b15b94aa0e9)

**Comment by Marcus98T** [comment]
I see. Well it's just hard for me to understand how Arphic (or other type foundries) designed the Chinese characters with their smart stroke technology in some proprietary font software, but anyway, it's not the point here.

Well if those strokes are designed that way as a just-in-case scenario, then there’s nothing we can do about it. I have struck out my previous comment if it means a waste of time “fixing” those duplicate points, but my initial comments about the inappropriate CN-style decorations will still stand.

**Comment by CoolMarvel43** [comment]
OK, I can verify that uni9FEE-JP (鿮) is sort of fixed (the 巾 component from the 冖 component is still connected which I think is a minor issue), so for now, I'm gonna close this issue.

<img width="292" alt="Screenshot 2024-08-12 at 05 18 09" src="https://github.com/user-attachments/assets/0478f671-ed07-43ce-bc1d-7da9a13ab6df">

I probably won't bother with the readme regarding the duplicate mention of the TW/HK 全 mappings as it's a trivial error. I think Adobe won't want to waste their time on very trivial issues.

<img width="797" alt="Screenshot 2024-08-12 at 05 21 07" src="https://github.com/user-attachments/assets/38780e1a-6e52-4234-95a5-c08d96edb9f6">
