### ISSUE TITLE
Request to open a discussion tab on this repository

### ISSUE THREAD

**Issue by Marcus98T** [adobe-fonts/source-han-serif#198]
Well, for anyone to ask a non-issue question and discuss some processes, may I request that Adobe open a discussion tab on this page?

I am still trying to learn and understand what's going on, but then all I heard is that Adobe is very busy with other things, their Creative Cloud software being of much higher priority, so nowadays the Source Han projects are not getting the attention they deserve, especially after Dr. Ken Lunde has already left. Also I believe @punchcutter has many other responsibilities that are not related to this font, such that he doesn't have the time to go through and discuss the many other issues this project has, or that they are put in the burner for the next major release, which will take several more years to realize. Multiple parties are also involved, from font designers like Arphic to standard bodies, so it is why the project is so complex.

It's been done for [this issue](https://github.com/adobe-fonts/source-han-sans/issues/452) on Sans, which was converted to [a discussion thread](https://github.com/adobe-fonts/source-han-sans/discussions/453), so the discussion tab was automatically opened. But actually, it didn't open the floodgates for anyone to ask questions on Sans.

Ultimately I have no right to know about this, and Adobe is not obligated to help or make the font perfect, but would it be beneficial for Adobe and everyone to have a discussion tab, just in case? Maybe it will involve a huge paradigm shift, so if Adobe thinks a discussion tab is not beneficial for them, they are free to close this issue as not planned.

**Comment by frankrolf** [comment]
Dear Marcus98T, have you ever read this?
https://github.com/orgs/community/discussions/5709

**Comment by Marcus98T** [comment]
Nope, and thanks for providing an appropriate link. I will close this issue.
