### ISSUE TITLE
Please think of duplicating the repository to CodePlex to help PRC users download the font.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-serif#2]
Due to disclosure-unsafe reasons (I think I already sent a screenshot to @kenlunde through Facebook message to explain this), GitHub download does not work well for PRC users.

I previously duplicated Source Han Sans repository to CodePlex to help PRC users access the font downloads. However, it is been a really long time ago and my focus in recent years is mainly on undergraduate Music History workloads and music composition / production studies, making me really hard to: 1) recall how to manage a repository on CodePlex; 2) find a time to manage these matters.

Still, an official mirror at CodePlex could be helpful, IMHO.

**Comment by showerying** [comment]
Isn't CodePlex shutting down?
And I just downloaded the source zip, the speed was around 2MB/s with Xunlei(without any VPNs or membership services), China Telecom.

**Comment by kenlunde** [comment]
Sorry, we will not set up any alternate repositories.

**Comment by ShikiSuen** [comment]
@showerying Not all places in Mainland PRC are having access issues to GitHub. This issue also depends on possible network service providers in different places.

**Comment by ShikiSuen** [comment]
@kenlunde What about, at least, thinking of offering alternative download mirrors within PRC?

**Comment by ShikiSuen** [comment]
@showerying You said one thing right. The CodePlex is shutting down:

https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/

**Comment by kenlunde** [comment]
For the sake of preserving history, I just restored the title of this issue. Please do not change it.

Setting up an official mirror site represents a management and logistical nightmare, which is why it won't happen. Our focus is to make the fonts and their sources available on GitHub, as well as providing the fonts for web and desktop use via Typekit.

**Comment by ShikiSuen** [comment]
@kenlunde Thanks for your explanaion. Then the rest question is whether you Adobe have that convenience to get the BitTorrent seeds ready for the public download of SHSans and SHSerif. It is not a joke that some people in some places always fail to download huge files from GitHub (even over 10MB). If using BitTorrent, some download service providers in Mainland PRC (e.g. Xunlei) will make its download boosted because they cache these popular downloads intact.

**Comment by ShikiSuen** [comment]
Finally a stable mirror in PRC is available now from Tsinghua University:
https://mirrors.tuna.tsinghua.edu.cn/adobe-fonts/
(Only compiled fonts at this moment. I just suggested them to sync the source files together.)

**Comment by ShikiSuen** [comment]
Update: Finally I gave up suggesting them to mirror the resource files. For those people who want the resource files, they will find a way to use VPN for stable download access to GitHub.

**Comment by kenlunde** [comment]
On the bright side, 99% of the people who care about these fonts need only the ready-to-install font resources, not their source files.
