### ISSUE TITLE
Incorrect Korean glyph for 寧

### ISSUE THREAD

**Issue by kevite** [adobe-fonts/source-han-serif#20]
There is supposed to be a long horizontal stroke like in Chinese but it seems to share a glyph with the Japanese version. This issue is also present in Source Han Sans.

![screen shot 2017-04-07 at 01 09 59](https://cloud.githubusercontent.com/assets/27000939/24791451/fac311bc-1b2e-11e7-865e-7e58d7f5658f.png)
http://www.zdic.net/z/18/zy/5BE7.htm
http://hanja.naver.com/hanja?q=%E5%AF%A7

**Comment by kenlunde** [comment]
Thank you. This is any easy fix, as I can easily map U+5BE7 in the KR CMap resource to the existing glyph _uni5BE7uE0100-JP_.

![uni5be7](https://cloud.githubusercontent.com/assets/3988788/24799501/4e1c8bec-1b50-11e7-8539-632592f6a97f.jpg)

I also made a note to fix this in _Source Han Sans_.

**Comment by kenlunde** [comment]
Consolidated with Issue #27.
