### ISSUE TITLE
Repeated contours in glyphs (serif version)

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#203]
Similar to https://github.com/adobe-fonts/source-han-sans/issues/463, some glyphs with repeated contours are spotted. Please see if any action is needed, thanks.

| Glyph             | Repeated contour groups
| ----------------- | -----------------
| uni1106uni1167uni11D9  | [12,15]                                                         
| uni1107uni1165uni11D9  | [10,13]                                                         
| uni110Cuni1167uni11D9  | [11,12]                                                         
| uni1159uni1175uni11D9  | [5,8]                                                           
| uni2600                | (The whole glyph)
| uni585A-TW             | [1,15];[2,16];[3,17]                                            
| uni607A-CN             | [7,11]                                                          
| uni61FEuE0101-JP       | [1,15];[2,16];[3,17]                                            
| uni9531-CN             | [7,9]                                                           
| uniB223                | [1,14]                                                          
| uniB245                | [9,11]                                                          
| uniB246                | [4,6]                                                           
| uniB249                | [6,8]                                                           
| uniB24A                | [6,8]                                                           
| uniCEAC                | [1,4]

**Comment by punchcutter** [comment]
Fixed in 2.003
