### ISSUE TITLE
Minor overlapping issue in uni6D04-JP

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#206]
__uni6D04-JP 洄__

The two contours in the bottom left of 回 should be overlapping, but isn't in the ExtraLight master:
![wui2](https://github.com/adobe-fonts/source-han-serif/assets/959433/312ee07c-4917-4ed9-85a4-6d07608e2105)

**Comment by punchcutter** [comment]
Fixed by 7889f11bf31170b5d092a083b357c8c8130f89e0
![serif206](https://github.com/user-attachments/assets/7b51e63f-74b9-4c95-8775-6aa7c0337fb0)
