### ISSUE TITLE
I'll do it: support for GB18030-2022 (⿼⿽⿾⿿㇯𠆾𠚤𪛗𪛘𪛙𪛚𪛛𪛜𪛝𱝫𱝬…)

### ISSUE THREAD

**Issue by MY1L** [adobe-fonts/source-han-serif#209]
### preface
see also (GB18030-2022) https://github.com/IBM/plex/issues/526

see also (Suzhou numerals and 々) https://github.com/adobe-fonts/source-han-serif/issues/131 ，2021年11月17日

### I made
3年了，等不起了，我直接做了。
![￫](https://github.com/adobe-fonts/source-han-serif/assets/58043328/717d71f1-30e6-4771-a09d-5351727b588c)

Add: ⿼⿽⿾⿿㇯𠆾𠚤𪛗𪛘𪛙𪛚𪛛𪛜𪛝𱝫𱝬
> 几乎照搬思源宋自身的设计——虽然说来奇怪：箭头的设计与思源宋自带的**黑体**箭头一致。（需要“宋体”箭头的人[请移步](https://github.com/MY1L/HanItalic)）

Improve design: 々〢〤〥〦〧〨〩〸〹〺㇒㇣㐃㔔㪳㫈
> 相关考据(中文)：[改善思源宋的“谚文汉字”㐃㪳㔔㫈…等](https://www.bilibili.com/read/cv29549665/)

#### [SourceHanSerifSCVF+.zip, v2024.1.23](https://github.com/adobe-fonts/source-han-serif/files/14053443/SourceHanSerifSCVF%2B.zip)
> [!NOTE]
> 此.zip包含如下用于生成可变字体的2个母版：
SourceHanSerifSCVF+ExtraLight.otf
SourceHanSerifSCVF+Heavy.otf
仅供字体设计师导入，不能直接当字体使用，仅支持如下字符：
U+2FFC	⿼
U+2FFD	⿽
U+2FFE	⿾
U+2FFF	⿿
U+3005	々
U+3022	〢
U+3024	〤
U+3025	〥
U+3026	〦
U+3027	〧
U+3028	〨
U+3029	〩
U+3038	〸
U+3039	〹
U+303A	〺
U+31D2	㇒
U+31E3	㇣
U+31EF	㇯
U+3403	㐃
U+3514	㔔
U+3AB3	㪳
U+3AC8	㫈
U+201BE	𠆾
U+206A4	𠚤
U+2A6D7	𪛗
U+2A6D8	𪛘
U+2A6D9	𪛙
U+2A6DA	𪛚
U+2A6DB	𪛛
U+2A6DC	𪛜
U+2A6DD	𪛝
U+3176B	𱝫
U+3176C	𱝬

以后再补充。

**Comment by punchcutter** [comment]
There's nothing to do for this issue. GB18030-2022 support has changed since the original announcement and we currently support Level 2 of the latest version. If something else changes we will update.

**Comment by NightFurySL2001** [comment]
@punchcutter these glyphs are different in GB18030 and slated to be changed in Unicode 17.0. Please update these glyphs:
U+3026 〦
U+3027 〧
U+3028 〨
U+3029 〩
