### ISSUE TITLE
Character not shown in PDF exported by LibreOffice

### ISSUE THREAD

**Issue by m13253** [adobe-fonts/source-han-serif#21]
![image](https://cloud.githubusercontent.com/assets/1808930/24799950/9c8195fe-1bd0-11e7-940e-cbb6f59d50bd.png)

```
Information for package libreoffice:
------------------------------------
Repository     : openSUSE-20170403-0            
Name           : libreoffice                    
Version        : 5.3.1.2-1.3                    
Arch           : x86_64                         
Vendor         : openSUSE                       
Installed Size : 269.0 MiB                      
Installed      : Yes                            
Status         : up-to-date                     
Source package : libreoffice-5.3.1.2-1.3.src    
```

This problem is also observed on Windows, where Mojibake is shown instead.

![image](https://cloud.githubusercontent.com/assets/1808930/24800034/e567ab5a-1bd0-11e7-848d-3703a975c84b.png)

I'm not sure it is totally LibreOffice's fault. I'll cross-post after confirmed.

**Comment by m13253** [comment]
Adobe Acrobat PDF printer also crashes if I use the "print" function:
![image](https://cloud.githubusercontent.com/assets/1808930/24800224/dcfffaac-1bd1-11e7-92da-0fb19a0dcae8.png)

```postscript
%%[ ProductName: Distiller ]%%
%%[ Error: undefinedresource; OffendingCommand: findresource ]%%

Stack:
/CIDFont
/SourceHanSerif-Bold
{--pop-- 4 --index-- --add--}
/SourceHanSerif-Bold-hf
/WinCharSetFFFF-H
/SourceHanSerif-BoldH


%%[ Flushing: rest of job (to end-of-file) will be ignored ]%%
%%[ Warning: PostScript error. No PDF file produced. ] %%
```

**Comment by kenlunde** [comment]
There are similar LibreOffice issues posted in the [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/issues) project, all of which point to LibreOffice issues. If the behavior is different than _Source Han Sans_, then it is probably due to LibreOffice not being able to deal with the style-linking that is present in _Source Han Serif_, which links Regular to Bold. If _fontconfig_ is used by LibreOffice, the Bold weight needs to be specified as the "Bold" style of the Regular weight, and not by explicit name.

**Comment by dantmnf** [comment]
@m13253 I found Adobe PDF printer won't work with OTC version font (in both LibreOffice and Microsoft Word), seems it's not the same issue.

**Comment by m13253** [comment]
I'm trying to figure out the cause of this problem and trying different font weights.
But I'm getting weird results. I will take notes here.
At least I'm now sure the problem is related to specific font weight settings.

Original document:
![image](https://cloud.githubusercontent.com/assets/1808930/24807988/efbd5826-1b7f-11e7-8771-833873f85c2b.png)

Rendered with "evince" (the Gnome PDF viewer):
![image](https://cloud.githubusercontent.com/assets/1808930/24808249/9fde235c-1b80-11e7-8ee6-00b25ea8e28f.png)

Rendered with PDF.js:
![image](https://cloud.githubusercontent.com/assets/1808930/24808413/37a09b16-1b81-11e7-87d2-cfda5092d1a1.png)

Rendered with Chrome PDF viewer:
![image](https://cloud.githubusercontent.com/assets/1808930/24808368/07b55f04-1b81-11e7-9d6e-cd8dea389cfa.png)

For reference, here are the files:
[Untitled 1.docx](https://github.com/adobe-fonts/source-han-serif/files/906119/Untitled.1.docx)
[Untitled 1.pdf](https://github.com/adobe-fonts/source-han-serif/files/906120/Untitled.1.pdf)

**Comment by miguelsousa** [comment]
@m13253 some of your screenshots suggest to me that the library that LibreOffice uses for generating PDFs does not fully support CID-keyed fonts.

I have no idea if LibreOffice uses Nodebox, but this issue might be useful for the LibreOffice developer that plans to look into the problem https://github.com/nodebox/opentype.js/issues/132

**Comment by kenlunde** [comment]
Another useful datapoint is whether _Source Han Sans_ and _Source Han Serif_ exhibit different behavior.

**Comment by m13253** [comment]
Bug cross-posted on https://bugs.documentfoundation.org/show_bug.cgi?id=107056

**Comment by khaledhosny** [comment]
LibreOffice does not support embedding CFF fonts in PDF, it converts them to Type1 fonts, any chance that there is something uncommon in Source Han fonts that would potentially affect such conversion?

**Comment by kenlunde** [comment]
@khaledhosny: You wrote:

> …any chance that there is something uncommon in Source Han fonts that would potentially affect such conversion?

Yes, their size.

**Comment by khaledhosny** [comment]
I thought about that, but they are subset as well so shouldn’t be a problem when only a few characters are used like the samples here.

**Comment by khaledhosny** [comment]
BTW, the reason pdf.js is showing fallback fonts is because OTS is rejecting the fonts pdf.js is generating for bad CharString data.

**Comment by kenlunde** [comment]
The source (original) fonts are not rejected by OTS, so the conversion process must be corrupting the data. Another possibility is the CFF size, not in terms of number of glyphs, but the number of bytes.

**Comment by miguelsousa** [comment]
@khaledhosny a CFF-to-Type1 converter will need to be aware that CID-keyed fonts (the "flavor" of CFF commonly used for CJK fonts) can have multiple hint dictionaries (FDArray) and that subroutines are stored and accessed differently. See Adobe Tech Note #5014 circa page 30 for a general overview.

**Comment by khaledhosny** [comment]
A quick look at the code shows there is some support for CID-keyed fonts, also the glyphs of the light font are fine so might be something different. Anyway it is clearly a LibreOffice bug, will try to debug it if I got some time. Thanks for the helpful pointers.

**Comment by KrasnayaPloshchad** [comment]
> LibreOffice does not support embedding CFF fonts in PDF, it converts them to Type1 fonts,

Is it possible to give LibreOffice an ability to embedding OT-CFF fonts dirctly in PDF?

**Comment by KrasnayaPloshchad** [comment]
LibreOffice 6.01 seems fixed it.

**Comment by KrasnayaPloshchad** [comment]
LibreOffice Chinese Community (LibreOffice 中文社区, http://www.libreofficechina.org/) also reported LibreOffice 5.4.5 fixed it too.
