### ISSUE TITLE
uni58D3-JP (壓) has minor overlapping issue in Heavy master

### ISSUE THREAD

**Issue by ChiuMing-Neko** [adobe-fonts/source-han-serif#212]
### Prerequisites

* [x] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong, the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [x] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [x] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

![圖片](https://github.com/adobe-fonts/source-han-serif/assets/84143394/d5b6d2b6-f2e0-4a0e-8754-089733e66ebd)

The horizontal line of the upper part of 冐 (猒's left) component seems like not positioned correctly.

**Comment by ChiuMing-Neko** [comment]
Also spot the overlapping issue of uni5A33-CN in the ExtraLight Master

![圖片](https://github.com/adobe-fonts/source-han-serif/assets/84143394/86a3ef69-5ee4-44dd-abf1-43b6f9981f83)

**Comment by punchcutter** [comment]
Fixed by 7889f11bf31170b5d092a083b357c8c8130f89e0

![serif212-58D3-JP](https://github.com/user-attachments/assets/4a116864-327d-475e-938a-5b1a4a2a04fd)
![serif212-5A33-CN](https://github.com/user-attachments/assets/1cb4ae22-666c-4f91-87db-415a6fa13ca8)
