### ISSUE TITLE
[Investigation] Proportional Kana and the fluency of horizontal reading.

### ISSUE THREAD

**Issue by ShikiSuen** [adobe-fonts/source-han-serif#22]
I am wondering whether the kana of SHSerif is mostly optimized for vertical texts (looks really beautiful to me).

Since I couldn't find a way (like that in SHSans) to enable proportional kana for SHSerif, at this moment I would better just just leave two screenshots here and see other people's opinion regarding the fluency of horizontal readability (instead of leaving my comments first). Possible questions are:

- Does any of you find that (if using this font at the current version 1.00) you couldn't read kana texts under horizontal mode as fast as that under vertical mode?

- Do you have any feel of inconsistency if reading kana texts using this font under horizontal mode?

![image](https://cloud.githubusercontent.com/assets/3164826/24818446/dac82e3c-1b9d-11e7-88c5-f1b766808040.png)

![image](https://cloud.githubusercontent.com/assets/3164826/24818452/df85ff76-1b9d-11e7-9402-c45eb06a634f.png)

To @kenlunde : I am afraid it is not fair to the designer for leaving such question here or giving my opinions to this question **until** there is an approach to enable proportional kana.

To Monokano (just in case of making him confused): I am aware of the differences between readability and legibility this time, and I don't mean to insult anyone. I just want to see if anyone shares the same doubtness with me.

**Comment by kenlunde** [comment]
Applying the 'palt' (H) or 'vpal' (V) GPOS features will enable proportional kana, and further enabling 'kern' (H) or 'vkrn' (V) will enable kerning, which mainly covers kana and punctuation. Actually, enabling 'kern' (H) or 'vkrn' (V) should automatically enable 'palt' (H) or 'vpal' (V), because the values specified in 'kern' (H) or 'vkrn' (V) assume that 'palt' (H) or 'vpal' (V) are enabled. Making the glyphs for kana proportional by default, or via separate glyphs, is a nonstarter for this project. Oh, and like _Source Han Sans_, all kana have separate horizontal and vertical forms, and not just the small kana.

**Comment by ShikiSuen** [comment]
@kenlunde Thanks for your confirmation. I finally found that it is the bug in Apple Pages 6.1 (4328) that its "typography options" does not show anything related to the access to those OpenType features you addressed just now. The TextEdit.app shipped with macOS 10.12.4 could do this, and I found that it looks consistent under horizontal mode with proporitonal kana enabled.

![image](https://cloud.githubusercontent.com/assets/3164826/24819183/cd2a3c2c-1ba0-11e7-9860-3817406641bf.png)

This makes this issue topic unnecessary to me anymore. You may think of closing this case if you feel necessary.

**Comment by ShikiSuen** [comment]
Oh. My current point (hope that it is right): The horizontal kana in SHSans is optimized for proportional kana only and does not look consistant on occasions without access to east-asian OpenType features. However, similar to SHSans, SHSerif has insufficient CID slots for horizontal kana glyphs under default monospace mode (with no east-asian OpenType features enabled).

Maybe this issue needs to be marked as "as designed".

**Comment by ShikiSuen** [comment]
@kenlunde Here comes another question (which I'm afraid that it is not important enough to post as another single issue):

Most computer users in Japan uses Microsoft Windows. It ships "MS P 明朝" as default serif font for Microsoft Office and Windows. There is no doubt that this is the most famous computer Mincho font in Japan. This font uses proportional kana as default. Does this lead to the essense of enabling proportional kana as default in SHSerif? Or do you think further marketing research / survey needs to be done to see whether there's more people prefers the monospaced "MS 明朝" instead?

P.S.: I am afraid that monospaced kana only makes horizontal Japanese text look inconsistent (with unnecessary spaces between kana glyphs) for most east-asian users who read texts mixed with Japanese, especially that serif fonts are not the primary choice of UI fonts of operating systems in these days. For those people who prefer monospaced kana (and usually also monospaced latin and numeric character glyphs), they could simply enable the "tnum" or "fwid" feature (if the font supports showing monospaced kana specifically through these features).
