### ISSUE TITLE
Consolidation of Glyph Correction Suggestions (See Issue #39)

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#27]
![image](https://cloud.githubusercontent.com/assets/8191296/24830995/6af6f58a-1cc3-11e7-9327-c7ff0e142ec0.png)
The TW glyph for U+4FB9 is in error. The second stroke of the top right hand component should be the shortest.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24831015/ee424b92-1cc3-11e7-8eff-b19da201a37a.png)
The TW glyph for U+58FE is in error. The correct glyph exists but is not mapped.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24831093/c86e405e-1cc5-11e7-9bd0-484bea0b9dc1.png)
The glyph for 夂 in the CN glyph is so wide compared to JP that it looks awkward and out of place compared to other characters in SHSerif.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24831128/8b52aa2e-1cc6-11e7-8dfe-6b09762c869c.png)
The glyph for 夊 in the TW glyphs are horribly wide compared to JP that it looks awkward and out of place compared to other characters in SHSerif.  The top two dots are also too far apart in the CN/TW version of U+5914.  The stroke thickness of the CN/TW version is also too thin comapred to the JP/KR version.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24831158/0ab8fcfa-1cc7-11e7-8cf8-b4c9ef99ef7e.png)

The TW glyph for U+591A should be the same as the JP/KR one and not the CN glyph.  The turning corner of the second stroke should be at about the middle of the fifth stroke instead of three-fourths.

Compare with the code charts:
![image](https://cloud.githubusercontent.com/assets/8191296/24831161/18f20672-1cc7-11e7-87f8-2889e579b0b8.png)

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24831918/ba761754-1cd6-11e7-8d9b-5fabfcb6b83f.png)
The 9th stroke of the TW glyph should be shorter than the 8th and 10th stroke.  The phonetic component is 𡈼 (middle stroke shortest) which is distinguished from 壬 in TW locale.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24838260/3cedd0dc-1d77-11e7-84e3-5622efe3b94f.png)

The CN glyphs of U+6660, U+92EE, U+9BCE are incorrect. The TW glyph of U+92EE is also incorrect.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24848429/52d512ac-1df9-11e7-9a1d-fe9a948da5d8.png)
U+5015: The second last stroke should be longer than the last stroke in the CN glyph.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24852076/b2373b8a-1e08-11e7-937f-6d17262ef942.png)

The CN glyph for characters containing "祭" as component are inconsistent. Sometimes they are open (in red) and sometimes they are closed (green).  Sometimes they share glyphs with JP (always open), sometimes they do not.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24874133/1e3449f2-1e56-11e7-9965-612a9f47d7d3.png)
U+68B1: The second last stroke should be 點 instead of 捺 according to the conventions of PRC and TW.

Attached are the code charts for reference:
![image](https://cloud.githubusercontent.com/assets/8191296/24874142/29614ba4-1e56-11e7-9ea6-3b1563c3c623.png)

**Comment by kenlunde** [comment]
The Heavy master of the CN glyphs for the following characters requires adjustment such that the two vertical strokes, the left of which curves to the left, are of uniform weight: U+4F5B 佛, U+602B 怫, U+62C2 拂, U+6C1F 氟, U+6CB8 沸, U+7829 砩, U+7ECB 绋. These characters are common in that all are in GB 2312. The following characters are in GB 2312, but their CN glyphs are not affected: U+5F17 弗, U+72D2 狒, U+8274 艴, and U+8D39 费.

**Comment by kenlunde** [comment]
Map U+58F3 to _uni58F3-JP_ in the TW CMap resource per Issue #26.

**Comment by kenlunde** [comment]
Map U+5BE7 to _uni5BE7uE0100-JP_ in the KR CMap resource per Issue #20.

**Comment by kenlunde** [comment]
Fix the glyphs _uni11ED_, _uni11ED.tjmo01_ through _uni11ED.tjmo04_ (4), _uniD7F5_, _uniD7F5.tjmo01_ through _uniD7F5.tjmo04_ (4), _uniD7F6_, and _uniD7F6.tjmo01_ through _uniD7F6.tjmo04_ (4) per Issue #6. Fix the glyphs _uni1178_, _uniD7B5_, and _uniD7B5.vjmo01_ per Issue #25. Also to be adjusted are the glyphs _uni118C.vjmo01_, _uni1190.vjmo01_, _uni1192.vjmo01_, and _uni1112uni119Euni11D9_. 22 glyphs in total.

**Comment by kenlunde** [comment]
Fix the glyphs _uni5F73-CN_ and _uni6C11-CN_ so that they are centered of more balanced within the em-box, and fix the interpolation issue in the JP glyph for U+9B58 (_uni9B58-JP_; Adobe-Japan1-6 CID+7307) per Issue #11.

**Comment by kenlunde** [comment]
Map U+5173 to _uni5173-CN_ in the KR CMap resource per Issue #5.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24919950/f794e050-1f17-11e7-8958-3379fd74d920.png)
The CN glyph for U+6AE3 is borderline incorrect...

**Comment by kenlunde** [comment]
@hfhchan: The placement of the Radical 140 component relative to the Radical 159 component suggests that the CN glyph for U+6AE3 櫣 is technically correct.

**Comment by kenlunde** [comment]
Fix the glyphs _uni5316uE0101-JP_ (Adobe-Japan1-6 CID+13665) and _uni82B1uE0101-JP_ (Adobe-Japan1-6 CID+13666) per Issue #14.

**Comment by kevite** [comment]
![screen shot 2017-04-11 at 10 46 45](https://cloud.githubusercontent.com/assets/27000939/24922743/3138cb60-1ea4-11e7-9cef-3da60e8b98dc.png)

The KR glyph for 屄 should have 八 under 宀, not 儿.

![17634338_10209324901179517_8965349634815638949_n](https://cloud.githubusercontent.com/assets/27000939/24922713/196bf6f6-1ea4-11e7-9619-bc7b7a880505.jpg)

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24926263/9f8cfbb6-1f2d-11e7-80d2-edc8fd2fc0ab.png)
CID 23598 at U+6C77 belongs at U+3CCA instead:

![image](https://cloud.githubusercontent.com/assets/8191296/24926298/b926c5fc-1f2d-11e7-99aa-54989f454aed.png)
![image](https://cloud.githubusercontent.com/assets/8191296/24926309/bf780d3a-1f2d-11e7-9b9f-2f31d1bab1e0.png)

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24926480/48182530-1f2e-11e7-8950-3f5c3d1cb088.png)

The dot for U+3CDA should touch the left hand 撇.

**Comment by acuteaccent** [comment]
`uni1140uni1175uni11D9` (ᅀᅵᇙ) and `uni114Cuni116Funi11D9` (ᅌᅯᇙ) are wrong.

**Comment by kenlunde** [comment]
Consolidated with Issue #39 (so that I can better track and respond to such issues).

**Comment by kenlunde** [comment]
@kevite: With regard to your U+5C44 屄 suggestion, this character is outside the scope of KS X 1001 and KS X 1002, so unless there is an existing glyph that is a better match for KR use, and there is not, no change will be made. However, this glyph is outside the scope of Adobe-Japan1-6, meaning that it is a candidate for removal in order to make room for HK glyphs in Version 2.000. If the glyph is not removed, I made a note to change it glyph to conform to KR conventions.

**Comment by acuteaccent** [comment]
@kenlunde: Just get rid of uni5C44-JP. I wonder why uni5C44-JP even exists. Use uni5C44-CN for the Japanese and Korean versions instead, like what you did in Source Han Sans for this character.

**Comment by kenlunde** [comment]
@acuteaccent: As my previous reply stated, this character is a candidate for removal to make room for HK glyphs (Version 2.000), so the chances of it remaining are slim at best. No glyphs will be removed in Version 1._xxx_, but the mappings can be changed to orphan them.

**Comment by kenlunde** [comment]
@acuteaccent: I received the corrected glyphs from Sandoll's designer last night, and she opted to tweak two additional glyphs that correspond to modern hangul syllables. The CID to glyph name mapping of all four glyphs is below (this is for interpreting the image at the end of this comment):

`CID+7257 = uniC625`
`CID+7537 = uniC73D`
`CID+13681 = uni1140uni1175uni11D9`
`CID+13702 = uni114Cuni116Funi11D9`

What was tweaked for the glyphs for U+C625 옥 and U+C73D 윽 was the relative size of the ㅇ component.

The glyphs shown below are from the ExtraLight, Medium, and Heavy weights:

![shserif-four-corrections](https://cloud.githubusercontent.com/assets/3988788/25043059/dfa3e354-20d1-11e7-973f-8f7ca305a498.jpg)

**Comment by acuteaccent** [comment]
Confirmed. The new glyphs look nice. Thank you!
