### ISSUE TITLE
Consolidation of Glyph Sharing Suggestions (See Issue #38)

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#28]
U+6641: There is no practical difference between the two different forms by the CN and JP glyph.

![image](https://cloud.githubusercontent.com/assets/8191296/24838053/11a1efa2-1d73-11e7-9727-2804924b0d90.png)
Legend: CN, TW, JP, KR, CN/JP overlaid

**Comment by hfhchan** [comment]
U+4F8D: There is no practical difference between the two different forms by the CN and JP glyph.
![image](https://cloud.githubusercontent.com/assets/8191296/24845840/2c28574c-1de8-11e7-8f17-75be877d0b6e.png)

**Comment by hfhchan** [comment]
U+504F: There is no practical difference between the two different forms by the TW and KR glyph.
![image](https://cloud.githubusercontent.com/assets/8191296/24848830/50f0bc0a-1dfb-11e7-8a94-cf80762ecaf0.png)

Attached are the design of the glyphs in the Unicode Code Charts:
![image](https://cloud.githubusercontent.com/assets/8191296/24848838/5d38c520-1dfb-11e7-8a50-0e909ad2ab71.png)
which indicates that the touching of the top right and bottom right components are also acceptable for Taiwan.

The counter for the top right hand component of the KR glyph is narrower and more in-line with the overall design of Source Han Serif. Thus, the glyph for KR could replace the one used for TW.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24926048/da6ee380-1f2c-11e7-9d67-aa2941ce014b.png)
No practical difference for U+6C35 (氵) -- exact same character offset by a few pixels only.

**Comment by kenlunde** [comment]
Consolidated with Issue #38 (so that I can better track and respond to such issues).
