### ISSUE TITLE
Design consistency of the CN glyphs

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#29]
In the separate CN glyphs produced by Sinotype, the 日 component is nearly consistently too long in the Light weight. 

Below are examples of characters where the CN glyph (red) is overlaid with the JP glyph (white).  Some of them have different glyphs for CN and some of them share the same glyph between CN and JP.  When the glyphs are not shared, CN's 日 is usually too long.

![image](https://cloud.githubusercontent.com/assets/8191296/24838111/0afcf434-1d74-11e7-9c7d-cbe54c4f5d31.png)
![image](https://cloud.githubusercontent.com/assets/8191296/24838123/49e83e74-1d74-11e7-9573-56ba9e99b37b.png)
![image](https://cloud.githubusercontent.com/assets/8191296/24838130/66e1ff42-1d74-11e7-842e-a514b52d6653.png)

This leads to all other weights except Black being affected.  The difference may seen subtle when characters are isolated but affects the rhythm of reading and causes whole blocks of text to look unbalanced.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24838206/0d48162c-1d76-11e7-95c7-84692f934fd0.png)
Some other examples with line drawn for illustration.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24845782/b245cafe-1de7-11e7-9732-886301c24598.png)
The CN glyph for U+4FFC looks like it belongs to a different font compared to the JP glyph.

**Comment by hfhchan** [comment]
The CN/TW glyph for U+500F has overly enlarged counters.  JP glyph included for reference:

![image](https://cloud.githubusercontent.com/assets/8191296/24848324/c7525dd4-1df8-11e7-9ed7-e4a0d7f6a1a8.png)

Bottom is a simulated version where the counter of the top component is harmonized with other glyphs.

**Comment by hfhchan** [comment]
Moved from https://github.com/adobe-fonts/source-han-serif/issues/27#issuecomment-292733979

![image](https://cloud.githubusercontent.com/assets/8191296/24831093/c86e405e-1cc5-11e7-9bd0-484bea0b9dc1.png)
The glyph for 夂 in the CN glyph is so wide compared to JP that it looks awkward and out of place compared to other characters in SHSerif.

**Comment by hfhchan** [comment]
Moved from https://github.com/adobe-fonts/source-han-serif/issues/27#issuecomment-292734414

![image](https://cloud.githubusercontent.com/assets/8191296/24831128/8b52aa2e-1cc6-11e7-8dfe-6b09762c869c.png)
The glyph for 夊 in the TW glyphs are horribly wide compared to JP that it looks awkward and out of place compared to other characters in SHSerif.  The top two dots are also too far apart in the CN/TW version of U+5914.  The stroke thickness of the CN/TW version is also too thin comapred to the JP/KR version.

**Comment by hfhchan** [comment]
![image](https://cloud.githubusercontent.com/assets/8191296/24917790/d46b2172-1f10-11e7-8b9e-7d63f93a74d4.png)
The design of U+6AB2 is too wide and not harmonious with U+7CF0 and U+3A5B.

**Comment by kenlunde** [comment]
Consolidated with Issue #36.
