### ISSUE TITLE
Enhancement: Incorrect Fallback Glyph for U+6902 (椂) on TW

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#32]
The fallback glyph for U+6902 (椂) on TW is currently CID 21954 which follows the CN conventions instead of the TW conventions.

![image](https://cloud.githubusercontent.com/assets/8191296/24874702/2ed1ffd2-1e58-11e7-933b-eedc2e365521.png)

A better fallback glyph already exists as 21953, which is more suitable for TW than 21954.

**Comment by hfhchan** [comment]
The fallback glyph for U+6903 (椃) on TW is currently CID 29156 which follows the CN conventions instead of the TW conventions.

![image](https://cloud.githubusercontent.com/assets/8191296/24874811/88e6d808-1e58-11e7-80a2-8d081d5efe84.png)

A better fallback glyph already exists as 21956, which is more suitable for TW than 21955.

**Comment by kenlunde** [comment]
Note that U+6902 椂 and U+6903 椃 will get an appropriate form when HK support is added in Version 2.000, thus the _as designed_ label, but I did set a note to map these characters to the JP glyphs as a temporary measure.

**Comment by hfhchan** [comment]
Hmm... U+4FFF 俿, U+458E 䖎 and U+4593 䖓 already bear similar treatment where the TW glyph is blank in the region-specific subsets and fallback from JP in the language-specific otfs.

I also found U+9BF1 鯱, U+88ED 裭, U+5A4B 婋, which could bear the same treatment.

**Comment by hfhchan** [comment]
The "incorrect" fallback to CN glyph also occurs for U+6947 楇 and U+7171 煱. Interestingly, the fallback TW glyph for U+5368 卨 is already overridden to that of JP.

**Comment by kenlunde** [comment]
The moment one goes beyond the scope of Big Five, the chances of encountering such fallback is relatively high. U+458E 䖎, U+4593 䖓, U+4FFF 俿, and U+5368 卨 are simply carry-overs from mapping overrides that were used in _Source Han Sans_.

Also, the left-side component of U+88ED 裭 and U+5A4B 婋 makes me want to leave them as-is.

**Comment by kenlunde** [comment]
Consolidated with Issue #37.
