### ISSUE TITLE
CN Design Oddity for 界 component

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#33]
The CN Design for characters containing 界 is rather odd in that the bottom 介 is written with 人 under 田 instead of 八 under 田:

![image](https://cloud.githubusercontent.com/assets/8191296/24878137/7ffaa8da-1e64-11e7-8287-7ffaa68c0de5.png)

As far as the code charts are concerned, the CN glyphs should match the JP glyphs with legs departing from 田 instead of departing under 田.
![image](https://cloud.githubusercontent.com/assets/8191296/24878172/b176d0f0-1e64-11e7-991f-5a8a5a34fac4.png)
![image](https://cloud.githubusercontent.com/assets/8191296/24878179/b854a50a-1e64-11e7-9187-024e3b601a76.png)
![image](https://cloud.githubusercontent.com/assets/8191296/24878188/bfd39caa-1e64-11e7-9ee9-b89d72030362.png)
![image](https://cloud.githubusercontent.com/assets/8191296/24878194/c3c456ec-1e64-11e7-93fb-4946a7bc169e.png)
![image](https://cloud.githubusercontent.com/assets/8191296/24878198/c8178eda-1e64-11e7-9c5f-39b533ac2d5c.png)

**Comment by kenlunde** [comment]
This is part of the typeface design, at least in terms of the CN glyphs.
