### ISSUE TITLE
Error glyph for U+4EBD

### ISSUE THREAD

**Issue by hfhchan** [adobe-fonts/source-han-serif#34]
Glyphs in Source Han Serif: (CN/TW/JP/KR)
![image](https://cloud.githubusercontent.com/assets/8191296/24895345/7fc94bd8-1ec2-11e7-8ef4-b765afe46f94.png)

Glyphs U+4EBD in Code Charts:
![image](https://cloud.githubusercontent.com/assets/8191296/24895376/94f119e6-1ec2-11e7-9a27-f41e7dbebcaf.png)

According to Unihan, the definition for U+4EBD is a kwukyel and the GK source is in agreement with that.    Therefore, the KR glyph should be CID 9777 instead of CID 9776. 

Meanwhile, CID 9776 should actually be a variant of U+4EBC instead of U+4EBD.  That variant is encoded in Extension B as U+204DB:
![image](https://cloud.githubusercontent.com/assets/8191296/24895481/2f658566-1ec3-11e7-9a60-0db7a0670233.png)

**Comment by kenlunde** [comment]
I know the reason for this error, and it's a bit too complex to explain here.

Anyway, this JP glyph is already targeted for removal for the Version 2.000 update, to make room for the incoming HK glyphs. But, until then, I will map U+4EBD to _uni4EBD-CN_ in the JP and KR CMap resources. The glyph _uni4EBD-JP_ will remain until

Also, this should have been added to #27, which you opened. A new issue was not necessary.

**Comment by kenlunde** [comment]
Consolidated with Issue #37.
