### ISSUE TITLE
Add more HKSCS characters so that Trad. Chinese variant is more usable for Hong Kong users

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#4]
First of all, congratulations and thanks for the great product.

The current release of Source Han Serif doesn't include most of the codepoints covered by HKSCS that included in Unicode as CJK Extension B or later. Looks to me that roughly about 1,700 codepoints have been excluded.

I have read the [Adobe CJK Blog article](https://blogs.adobe.com/CCJKType/2017/04/source-han-serif-history-development.html#comments). While I fully understand the rationale behind this move, this unfortunately renders the current revision of Source Han Serif not very usable for Hong Kong people, as a number of those Ext-B HKSCS characters are frequently used in our region and are missing.

As I am unable to predict how long we need to wait for the new version of HKSCS and the HK variant of Source Han Sans and Serif to be released, I would like to suggest to include some more HKSCS characters to the current Traditional Chinese variant as an _interim_ solution, so that it can be more usable to Hong Kong users. Of course, this is not needed if the release date is not far off.

I am going to suggest 61 characters to be added. They are further divided into 3 levels base on their frequency of use.

Level 1: 35 characters. Frequently used, lacking those will certainly impact daily experience.

Level 2: 11 characters. Usually seen, so suggest to include.

Level 3: 15 characters. Even less frequently used, although still occasionally seen. May bring minor inconvenience when ignored.

The problem of this list is that it is crafted in an hour base on my personal experience, so they cannot be considered fully scientific (The H-source in IICORE still lacks some frequently used characters so cannot be fully relied upon). That said, I am quite confident that Level 1 characters are badly needed for Hongkongers.

Thank you for considering my request.

## Level 1

| Codepoint | Character |
| --------- | --------- |
| U+20779  |  𠝹# |
| U+20C78  |  𠱸# |
| U+20E73  |  𠹳 |
| U+20E9D  |  𠺝# |
| U+20EF9  |  𠻹#* |
| U+20F4C  |  𠽌# |
| U+2107B  |  𡁻# |
| U+210C1  |  𡃁#* |
| U+220C7  |  𢃇# |
| U+22B43  |  𢭃# |
| U+22C51  |  𢱑# |
| U+22C55  |  𢱕# |
| U+22CC2  |  𢳂# |
| U+22D8D  |  𢶍 |
| U+233F4  |  𣏴 |
| U+244D3  |  𤓓# |
| U+24DEA  |  𤷪# |
| U+24EA7  |  𤺧 |
| U+24F0E  |  𤼎 |
| U+2512B  |  𥄫#* |
| U+25E49  |  𥹉 |
| U+26258  |  𦉘# |
| U+267CC  |  𦟌# |
| U+269F2  |  𦧲# |
| U+282E2  |  𨋢# |
| U+28CCA  |  𨳊# |
| U+28CCD  |  𨳍# |
| U+28CD2  |  𨳒# |
| U+28D99  |  𨶙* |
| U+29D98  |  𩶘# |
| U+29EAC  |  𩺬 |
| U+23CB7  |  𣲷# |
| U+269FA  |  𦧺# |
| U+2815D  |  𨅝# |
| U+20F31  |  𠼱 |

## Level 2

These 11 characters are sometimes used.

| Codepoint | Character |
| --------- | --------- |
| U+22EB3  |  𢺳# |
| U+20BA9  |  𠮩 |
| U+20C41  |  𠱁 |
| U+20C96  |  𠲖# |
| U+20D71  |  𠵱 |
| U+20E4C  |  𠹌* |
| U+20E98  |  𠺘 |
| U+2197C  |  𡥼 |
| U+22CA1  |  𢲡 |
| U+2829B  |  𨊛 |
| U+20F90  |  𠾐 |

## Level 3

These 15 characters are even less frequently used, although still occasionally seen.

| Codepoint | Character |
| --------- | --------- |
| U+20F2E  |  𠼮# |
| U+227B5  |  𢞵# |
| U+22BCA  |  𢯊# |
| U+20F2D  |  𠼭# |
| U+20731  |  𠜱# |
| U+2105C  |  𡁜# |
| U+22BCE  |  𢯎* |
| U+22D08  |  𢴈 |
| U+22D4C  |  𢵌 |
| U+22DEE  |  𢷮# |
| U+24DB8  |  𤶸# |
| U+27A3E  |  𧨾# |
| U+28207  |  𨈇# |
| U+2A0B9  |  𪂹 |
| U+2F8CD  |  晉 |

#: Also in IICORE when "H" source.
*: HK glyph different from TW as per standard.

**Comment by tamcy** [comment]
Oops, just discovered that the currently "included" HKSCS characters are actually using C-source glyphs. In this case it wouldn't be very meaningful to include more characters 😕.

**Comment by kenlunde** [comment]
The lack of meaningful HK support is clearly mentioned in multiple places in the ReadMe file, and providing HK support in a piecemeal fashion is a nonstarter due to the scope of the project. The Version 2.000 update will not only provide proper HK support, but it will do so via separate HK fonts and font instances.
