### ISSUE TITLE
Korean name of the product is identical to another typeface

### ISSUE THREAD

**Issue by celestialphineas** [adobe-fonts/source-han-serif#41]
The Korean name of Source Han Serif, “본명조”, transcribed in Hanja is “本明朝”, which is identical to another Mincho typeface in Japan: “本明朝”.

See: http://www.morisawa.co.jp/fonts/specimen/1770

**Comment by acuteaccent** [comment]
Well, since the official Korean name of Source Han Serif is not written in hanja, there will be no conflict.

**Comment by acuteaccent** [comment]
There is no conflict in Chinese and Japanese either.

In Chinese, Source Han Serif is called 思源宋体/思源宋體 and that Morisawa's font is would be called 本明朝.
In Japanese, Source Han Serif is called 源ノ明朝 and that Morisawa's font is called 本明朝.

What about in Korean? Source Han Serif is called 본명조 and that Morisawa's font can be called 혼명조, transcribing the original Japanese reading of 本 (which is ほん, according to that official page) into hangul (혼).

No conflict at all, no problem at all. How simple.

**Comment by kenlunde** [comment]
As @acuteaccent kindly pointed out, there is no naming conflict, because 본명조 is a completely different script than 本明朝. None of the characters are identical.

**Comment by celestialphineas** [comment]
Many thanks. And that is to say the Korean name “본명조” should never be transcribed in Hanja, right?

**Comment by kenlunde** [comment]
Right, and the Korean name of _Source Han Sans_ has never used 本 instead of 본. In fact, this is the first time I have seen the Korean versions of the _Source Han_ fonts shown using names that include hanja.

**Comment by acuteaccent** [comment]
Well, when you are writing about Source Han Serif in Chinese or Japanese, you will use 思源宋体/思源宋體 or 源ノ明朝. You will not use 本明朝 when referring to Source Han Serif anyway.

**Comment by celestialphineas** [comment]
I can get your point. But my point is: “본” referring to “source” is not a purely native word, but of Chinese origin “本”.

See: https://en.wiktionary.org/wiki/%EB%B3%B8

It seems to me that the name has a way of transcribing into Hanja with no doubt, though very unlikely to see this (please forgive me if I make a big mistake; I don't really know Japanese and Korean). Indeed SHSerif is referred to as 源ノ明朝 in Japan, and in Korea the Morisawa's typeface should be transcribed as 혼명조. But there still exists a possibility of referring SHSerif's Korean name in Chinese, and this is the situation where the confusion may occur.

Of course I wouldn't expect SHSerif to change its product name. Many thanks to the kindly help from Dr. Ken Lunde and @acuteaccent. I am only here to remind people that there is a potential confusion.

**Comment by kenlunde** [comment]
@celestialphineas: There are precisely five names for this typeface: _Source Han Serif_ (English), 思源宋体 (Simplified Chinese), 思源宋體 (Traditional Chinese), 源ノ明朝 (Japanese), and 본명조 (Korean). Any other derivatations are merely creations, and have no bearing on this typeface. Let's stop [beating a dead horse](https://en.wikipedia.org/wiki/Flogging_a_dead_horse).
