### ISSUE TITLE
Suggest a better download page & guide

### ISSUE THREAD

**Issue by Explorer09** [adobe-fonts/source-han-serif#44]
The current [download readme](https://github.com/adobe-fonts/source-han-serif/blob/release/README.md) and the [download guide](https://github.com/adobe-fonts/source-han-serif/blob/release/download-guide-source-han.pdf) is still too much text and complicated in my opinion.

I would suggest reworking the download page to be more user-friendly.
In particular:

1. Since Super OTC will eventually be the preferred format of Source Han
(Sans or Serif) installations, at least on desktop system, I think it's best to
put them as the first one on the page.

2. It's good to also mention the OS requirements just above the links on the
readme, since it plays a big role on choosing which format to download.
(TODO: mention also Linux/Unix requirements. Since there are so many
distributions out there, it's better to mention the FreeType and fontconfig
versions instead.)

3. OTCs should be packed as one ZIP file per weight, instead of multiple
weights together. Reason: Users who would download these are probably people
who only need specific weights. And the ZIP files aren't solid compression, so
there's little size saving when they were packed together. Packing them as
individual weights would help user same bandwidth if he needs, for example,
only Regular and Bold.

Below is the download readme page I would propose:

```
## Downloading Source Han (Sans or Serif)

### Super OTC

Download this if you want all languages and all weights.

This format requires OS X 10.8 (Mountain Lion) or later, iOS 7 or later, or
Windows 10 Version 1703 (Creators Update) or later.

[Super OTC part 1] + [Super OTC Part 2]

The ZIP file for the Super OTC has been necessarily split into two parts, due
to GitHub's 100MB file size limit. Unfortunately, the built-in
_Archive Utility_ app of macOS doesn't support split ZIP files, and we
therefore recommend that you download and installed the
[Unarchiver](http://unarchiver.c3.cx/unarchiver) app. To unzip, either drag the
Part 2 file (the one with ".zip" extension) onto the _Unarchiver_ app,
or use Control-Click to open it by specifying that app (after installing the
_Unarchiver_ app, you may also be able to simply double-click the Part 2 file).
Either of these actions will combine the two parts and unzip them. For Windows,
select the Part 2 file, then use the "Extract All" context menu to combine the
two parts and unzip them.

### OTCs

Download this if you want all languages but only specific weights.

This format requires OS X 10.8 (Mountain Lion) or later, iOS 7 or later, or
Windows 10 Version 1607 (Anniversary Update) or later.

[Extra Light], [Light], [Regular], [Medium], [SemiBold], [Bold], [Heavy]

### Language-specific OTFs

Download this if you prefer only one language in your deployment, but wish to
have Pan-CJK support of the characters. (Or when the aforementioned OTC format
doesn't work with your operating system.)

Glyphs of other regional variants may be accessed by labeling the text with a
language. Your software needs to support OpenType 'locl' (Localized Forms) GSUB
feature. For example, in Adobe InDesign, you may use Language menu in the
Character panel to tag languages.

Font names containing the "HW" letters are variants that use half-width Latin
and digits by default.

If you only need specific weights, download individual files from
[the OTF directory](OTF).

Simplified Chinese:
[ExtraLight + Light + Regular + Medium] & [SemiBold + Bold + Heavy] & [HW Regular + HW Bold]

Traditional Chinese:
[ExtraLight + Light + Regular + Medium] & [SemiBold + Bold + Heavy] & [HW Regular + HW Bold]

Japanese:
[ExtraLight + Light + Regular + Medium] & [SemiBold + Bold + Heavy] & [HW Regular + HW Bold]

Korean:
[ExtraLight + Light + Regular + Medium] & [SemiBold + Bold + Heavy] & [HW Regular + HW Bold]

### Region-specific Subset OTFs

Download this if you need only characters of a particular language or region,
or you need to use regional variants on software that doesn't support
language-tagging or 'locl' GSUB feature. **Choose this if you're not sure
which format you should choose.**

The ZIP files contains all weights. If you only need specific weights, download
individual files from [the SubsetOTF directory](SubsetOTF).

[China], [Taiwan], [Hong Kong], [Japan], [Korea]
```

**Comment by kenlunde** [comment]
Thank you for the suggested changes. I think that the following comment should also be included in the OTC section (it is in the OTF and subset OTF sections), and the ZIP files should remain as-is (meaning two of them with multiple weights):

> If you only need specific weights, download individual files from [the OTC directory](OTC).

**Comment by kenlunde** [comment]
Done. I will make a comparable change to the README.md file in the [_Source Han Sans_ release branch](https://github.com/adobe-fonts/source-han-sans/tree/release) later today.
