### ISSUE TITLE
Why does NotoSerifCJKtc appear using Simplified Chinese glyphs on an Android app?

### ISSUE THREAD

**Issue by LNDDYL** [adobe-fonts/source-han-serif#46]
所使用的字型：NotoSerifCJK**tc**-Black.otf 【注意是tc】

![photo_2017-04-25_14-19-13](https://cloud.githubusercontent.com/assets/4318463/25371355/01831acc-29c3-11e7-891c-f896b07b475c.jpg)
^在Android中顯示為中國（大陸）標準字形，此為錯誤顯示。

![default](https://cloud.githubusercontent.com/assets/4318463/25371363/117326f2-29c3-11e7-9899-b8109e37e6ed.png)
^在Windows 7中顯示為臺灣的國字標準字體，此為正確顯示。

**Comment by s8321414** [comment]
Please use English to describe your issue.

**Comment by kenlunde** [comment]
For Android OS, the 'locl' GSUB feature is somehow being triggered, which can be done only if a language setting specifies Simplified Chinese. The default glyphs for that particular font are those that display correctly on Windows. If you cannot find a setting that is set to Simplified Chinese, this is likely a [UnicodePad](https://play.google.com/store/apps/details?id=jp.ddo.hotmist.unicodepad) app issue.
