### ISSUE TITLE
source-han-serif TC Issues

### ISSUE THREAD

**Issue by HwangTW** [adobe-fonts/source-han-serif#48]
I use  Libreoffice and source-han-serif-heavy TC Export PDF will Error
http://i.imgur.com/EGTRqBf.png
then use Libreoffice and source-han-serif TC Export PDF then can be fine
example: http://i.imgur.com/yhfW61E.png
but use Libreoffice and source-han-serif TW Export PDF will OK
can you check source-han-serif TC Building?

**Comment by kenlunde** [comment]
Closed as a duplicate of #21.

**Comment by KrasnayaPloshchad** [comment]
You can try to print via PDFCreator to avoid that.
