### ISSUE TITLE
Question of Glyph design principle.

### ISSUE THREAD

**Issue by dadasutasudadas** [adobe-fonts/source-han-serif#52]
The Source Han Serif fonts are really easy to use.
I appreciate this project.
At the same time, I wanted to know about the character form principle of Source Hans Serif  #TC.
While using the fonts, I noticed that the Traditional Chinese characters seem different from the Source Han Sans fonts.
For example, the left “radical” in 迌 (U+8FCC) is different between Sans and Serif.
The same applies to逈(U+9008) and 迁 (U+8FC1).
I want to use these fonts to the full, so I will appreciated it very much if I could know the Glyph design principle. 

![8fcc](https://cloud.githubusercontent.com/assets/21096794/25575201/0b191eac-2e90-11e7-951b-e0dd9725a24c.JPG)

**Comment by hfhchan** [comment]
U+8FCC is a character contained in HKSCS.  Since HKSCS is out of the scope of the current version of Source Han Serif, no TC glyph for U+8FCC exists, and the one for China is used instead.

For Source Han Sans, HKSCS was in the scope, thus a TC glyph for U+8FCC exists.

**Comment by kenlunde** [comment]
@hfhchan is correct, and his reply is precisely what I would have written if I had not been asleep.
