### ISSUE TITLE
Mapping Difference between Source Han Sans and Source Han Serif

### ISSUE THREAD

**Issue by dadasutasudadas** [adobe-fonts/source-han-serif#53]
Three characters were found in Source Han Serif TC that have different mapping with Source Han Sans TC.
They are倉(U+5009), 釉(U+91C9) and 隉(U+9689).
![3glyphsquestion](https://cloud.githubusercontent.com/assets/21096794/25609153/e65fd262-2f58-11e7-946c-d0c773afe192.JPG)

It would be useful if they were mapped as the following, as they are in their equivalent San-serif fonts.
倉(U+5009) → cid10273
釉(U+91C9) → cid42210
隉(U+9689) → cid44061

**Comment by hfhchan** [comment]
For U+5009, the mapping for Source Han Serif TC needs to be fixed, the correct form is the one on the top.

For U+91C9 and U+9689, the glyph/mapping for Source Han Sans TC needs to be fixed -- the correct form are the ones at the bottom.

**Comment by kenlunde** [comment]
I have consolidated this issue with #37 for U+5009 倉, and with [Source Han Sans Issue 99](https://github.com/adobe-fonts/source-han-sans/issues/99) (although it really belongs in [Issue 115](https://github.com/adobe-fonts/source-han-sans/issues/115)).
