### ISSUE TITLE
Lacking glyphs from Polish and Czech language

### ISSUE THREAD

**Issue by starkshaw** [adobe-fonts/source-han-serif#54]
<img width="1308" alt="screen shot 2017-05-04 at 00 26 19" src="https://cloud.githubusercontent.com/assets/9618357/25685576/67ae058e-3060-11e7-8741-13f010df1f30.png">

As shown above, Noto Serif CJK SC doesn't contain some letters in Polish and Czech, those have been fallbacked to Calibri. Compare to Helvetica Neue at the top lines.

**Comment by starkshaw** [comment]
Note that first line of both sections are Polish letters, second lines are Czech letters.

**Comment by frankrolf** [comment]
@starkshaw If you need to typeset Czech or Polish, please use https://github.com/adobe-fonts/source-serif-pro

**Comment by starkshaw** [comment]
Hi Mr. Greißhammer,
    Thanks for your reply. I am just curious if they are left blank intentionally. ✌️

**Comment by frankrolf** [comment]
Since this project is targeted at Pan-CJK typesetting (and the font files are filled to capacity), some glyphs had to be removed in favor of CJK glyphs. I am sure @kenlunde knows more.

**Comment by kenlunde** [comment]
As my esteemed colleague @frankrolf kindly pointed out, the _Source Han_ families are Pan-CJK, not Pan-Unicode, fonts. The glyphs for the characters you referenced are way outside the scope of the glyph set. We'd add italic forms of the existing Western glyphs before considering adding glyphs for those particular characters.

**Comment by frankrolf** [comment]
Just for clarification: please note that Source Serif (without _Han_) supports all of the above characters.

**Comment by kenlunde** [comment]
@starkshaw: In case it helps to clarify the scope of the Western portion of the _Source Han_ typefaces, the "Latin, Greek & Cyrillic Glyphs” section that starts at the bottom of page 7 of the [ReadMe](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) (PDF) states the following: _Included in all font resources is a rich set of Latin glyphs that support not only ASCII and ISO/IEC 8859-1 (aka ISO Latin 1), but also the characters that are necessary for broadly-used CJK transliteration and transcription systems, along with those that are necessary for Latin-based Vietnamese._
