### ISSUE TITLE
Design difference between Source Han Sans K and Source Han Serif K 

### ISSUE THREAD

**Issue by dadasutasudadas** [adobe-fonts/source-han-serif#59]
Thank you for your clear explanation on the KR glyph.
The CJK Type Blog was very helpful.
I noticed 15 characters that differ in character form concerning KS X 1001 and 1002 between Source han serif K and Source han sans K.
倂 U+5002, 剪 U+526A, 墁 U+5881, 栞 U+681E, 梏 U+688F, 櫝 U+6ADD, 汋 U+6C4B, 瀆 U+7006, 炷 U+70B7, 牘 U+7258, 犢 U+72A2, 犳 U+72B3, 猀 U+7300, 琱 U+7431, 瑤 U+7464

![kr_diff](https://cloud.githubusercontent.com/assets/21096794/25937910/713a3934-3668-11e7-9acb-71d9fc9f755b.JPG)

**Comment by kenlunde** [comment]
U+526A 剪, U+5881 墁, U+681E 栞, U+688F 梏, U+6ADD 櫝, U+6C4B 汋, U+7006 瀆, U+70B7 炷, U+7258 牘, U+72A2 犢, U+72B3 犳, and U+7431 琱 are handled by mapping these characters to the corresponding CN glyphs in the KR CMap resource, and this is now recorded in Issue #37.

U+5002 倂, U+7300 猀 (outside the scope of KS X 1001 and KS X 1002), and U+7464 瑤 require slightly different treatment.

**Comment by kenlunde** [comment]
For U+5002 倂, the difference can actually be traced back to differences in _Kozuka Mincho_ and _Kozuka Gothic_, and the former, and therefore _Source Han Serif_, is correct. However, this means that the JP glyph for U+5002 倂 in _Source Han Sans_, _uni5002-JP_, needs to be corrected, and both _Source Han Sans_ and _Source Han Serif_ need a KR glyph for U+5002 倂, _uni5002-KR_, to be added.

For U+7300 猀, although this character is outside the scope of the two KS standards, I plan to remove its JP glyph in Version 2.000 (it's already a candidate for removal), and will map U+7300 猀 to the CN glyph, _uni7300-CN_, in the JP and KR CMap resources.

For U+7464 瑤, this looks like a _Source Han Sans_ issue that affects its JP glyph, which is also used in the KR CMap resource. I made a note to check that glyph as part of its Version 2.000 update.

**Comment by dadasutasudadas** [comment]
Sorry to have duplicated a past issue. Thank you for your clear reply.

**Comment by kenlunde** [comment]
@dadasutasudadas: Thank you for the report, which included several actionable items. When developing such a large and complex project, the presence of issues is expected. Luckily, open source projects have a good mechanism for reporting and tracking issues.

**Comment by kenlunde** [comment]
For U+681E 栞, I determined that the correct course of action is to leave the current mapping as-is, meaning that the JP glyph, _uni681E-JP_, is used, and that the corresponding mapping needs to be fixed in _Source Han Sans_ (see [_Source Han Sans_ Issue 177](https://github.com/adobe-fonts/source-han-sans/issues/177)).
