### ISSUE TITLE
Glyphs of U+11ED ᇭ, U+D7F5 ퟵ, U+D7F6 ퟶ

### ISSUE THREAD

**Issue by acuteaccent** [adobe-fonts/source-han-serif#6]
Yesieung (ㆁ), not ieung (ㅇ). This includes .tjmo0[1-4] glyphs of those three hangul jamo characters as well.

**Comment by kenlunde** [comment]
Thank you. I will report this issue to Sandoll's designer for consideration.

**Comment by acuteaccent** [comment]
Investigating? Not a bug?

**Comment by kenlunde** [comment]
Sandoll's designer confirmed this bug, which affects the following 15 glyphs: _uni11ED_, _uni11ED.tjmo01_ through _uni11ED.tjmo04_ (4), _uniD7F5_, _uniD7F5.tjmo01_ through _uniD7F5.tjmo04_ (4), _uniD7F6_, and _uniD7F6.tjmo01_ through _uniD7F6.tjmo04_ (4). The first update will reflect fixed versions of these glyphs.

**Comment by kenlunde** [comment]
`[uni1161.vjmo01 uni1163.vjmo01 uni116A.vjmo01 uni1184.vjmo01 uni1189.vjmo01 uni118E.vjmo01 uni11A6.vjmo01 uniD7B2.vjmo01 uniD7B9.vjmo01 uniD7C5.vjmo01] + any T = tjmo01
`
`[uni1165.vjmo01 uni1167.vjmo01 uni116C.vjmo01 uni116F.vjmo01 uni1171.vjmo01 uni1174.vjmo01 uni1175.vjmo01 uni117F.vjmo01 uni1186.vjmo01 uni1188.vjmo01 uni118F.vjmo01 uni1191.vjmo01 uni1194.vjmo01 uni119D.vjmo01 uni119F.vjmo01 uni11A1.vjmo01 uni11A5.vjmo01 uniD7B0.vjmo01 uniD7B4.vjmo01 uniD7B5.vjmo01 uniD7BA.vjmo01] + any T = tjmo02`

`[uni1162.vjmo01 uni1164.vjmo01 uni1166.vjmo01 uni1168.vjmo01 uni116B.vjmo01 uni1170.vjmo01 uni1180.vjmo01 uni1181.vjmo01 uni1185.vjmo01 uni118A.vjmo01 uni118C.vjmo01 uni1190.vjmo01 uni1192.vjmo01 uni1198.vjmo01 uni1199.vjmo01 uni11A7.vjmo01 uniD7B3.vjmo01 uniD7B6.vjmo01 uniD7B7.vjmo01 uniD7BB.vjmo01 uniD7BE.vjmo01 uniD7BF.vjmo01 uniD7C0.vjmo01 uniD7C4.vjmo01 uniD7C6.vjmo01] + any T = tjmo03`

`[uni1160.vjmo01 uni1169.vjmo01 uni116D.vjmo01 uni116E.vjmo01 uni1172.vjmo01 uni1173.vjmo01 uni1176.vjmo01 -uni117E.vjmo01 uni1182.vjmo01 uni1183.vjmo01 uni1187.vjmo01 uni118B.vjmo01 uni118D.vjmo01 uni1193.vjmo01 uni1195.vjmo01 -uni1197.vjmo01 uni119A.vjmo01 -uni119C.vjmo01 uni119E.vjmo01 uni11A0.vjmo01 uni11A2.vjmo01 -uni11A4.vjmo01 uniD7B1.vjmo01 uniD7B8.vjmo01 uniD7BC.vjmo01 uniD7BD.vjmo01 uniD7C1.vjmo01 -uniD7C3.vjmo01] + any T = tjmo04`

**Comment by kenlunde** [comment]
To follow up on this, in addition to fixing the 15 glyphs that were originally reported, Sandoll's designer decided to adjust the following four additional glyphs: _uni118C.vjmo01_, _uni1190.vjmo01_, _uni1192.vjmo01_, and _uni1112uni119Euni11D9_. The last glyph is one of the 500 high-frequency archaic hangul syllables.

**Comment by acuteaccent** [comment]
Thank you for letting me know those conditions. Do those apply to Source Han Sans as well, without any differences?

**Comment by kenlunde** [comment]
Yes, _Source Han Sans_ is the same.

**Comment by acuteaccent** [comment]
Just in case, can you please list the conditions for ljmo0[1-6] as well? I just want to check whether what I thought is the same as the ones defined in the font.

**Comment by acuteaccent** [comment]
The one about uni1112uni119Euni11D9 is interesting. I wonder how ᄒᆞᇙ became 흐ᇙ.

**Comment by kenlunde** [comment]
I received the 19 updated glyphs from Sandoll's designer and processed them this morning. The PDF synopsis below shows the ExtraLight, Medium, and Heavy weights, and the combining glyphs are shown before I shifted them to the left and zero-out their horizontal advances (so that they are easier to see here). Also, the CIDs don't correspond to _Source Han Serif_ CIDs, but are for the back-end source data.

![fixed-shserif-hangul-jamo](https://cloud.githubusercontent.com/assets/3988788/24815005/88e9ecdc-1b88-11e7-8f00-1520e2092b18.jpg)

**Comment by kenlunde** [comment]
Here are the CID to working glyph name correspondences:

`238	uni11ED`
`12745	uni11ED.tjmo01`
`12882	uni11ED.tjmo02`
`13019	uni11ED.tjmo03`
`13156	uni11ED.tjmo04`
`506	uniD7F5`
`12806	uniD7F5.tjmo01`
`12943	uniD7F5.tjmo02`
`13080	uniD7F5.tjmo03`
`13217	uniD7F5.tjmo04`
`507	uniD7F6`
`12807	uniD7F6.tjmo01`
`12944	uniD7F6.tjmo02`
`13081	uniD7F6.tjmo03`
`13218	uniD7F6.tjmo04`
`12530	uni118C.vjmo01`
`12534	uni1190.vjmo01`
`12536	uni1192.vjmo01`
`13487	uni1112uni119Euni11D9`

**Comment by kenlunde** [comment]
Any L + `[uni1161 through uni1168 uni1175 uni1198 uni1199 uni119D uni11A5 uniD7BE through uniD7C0 uniD7C4]` + any T = _ljmo01_
Any L + `[uni1160 uni1169 uni116D uni116E uni1172 uni1173 uni1182 uni1183 uni1187 uni118D uni1193 uni1195 uni1196 uni119E uni11A0 uni11A2 uniD7B1 uniD7B8 uniD7BC]` + any T = _ljmo02_
Any L + `[uni116A through uni116C uni116F through uni1171 uni1174 uni1176 through uni1181 uni1184 through uni1186 uni1188 through uni118C uni118E through uni1192 uni1194 uni1197 uni119A through uni119C uni119F uni11A1 uni11A3 uni11A4 uni11A6 uni11A7 uniD7B0 uniD7B2 through uniD7B7 uniD7B9 through uniD7BB uniD7BD uniD7C1 through uniD7C3 uniD7C5 uniD7C6]` + any T = _ljmo03_

_lmjo04_ through _ljmo06_ are identical to _lmjo01_ through _ljmo03_, respectively, except that the "any T" portion is removed from their context.

**Comment by acuteaccent** [comment]
For those three vjmo01 glyphs: The new design is better, as they are followed by a T. Under the old design, it is hard to see the short horizontal strokes.

Conditions for ljmo: Thank you. They are the same as I thought.

**Comment by acuteaccent** [comment]
Note to self (and to others who want to test archaic hangul jamo in Source Han Sans and Source Han Serif)

ljmo01: when followed by [ᅡ, ᅢ, ᅣ, ᅤ, ᅥ, ᅦ, ᅧ, ᅨ, ᅵ / ᆘ, ᆙ, ᆝ, ᆥ, ힾ, ힿ, ퟀ, ퟄ] + any T
ljmo02: when followed by [ᅩ, ᅭ, ᅮ, ᅲ, ᅳ / ᅠ (jungseong filler), ᆂ, ᆃ, ᆇ, ᆍ, ᆓ, ᆕ, ᆖ, ᆞ, ᆠ, ᆢ, ힱ, ힸ, ힼ] + any T
ljmo03: when followed by [ᅪ, ᅫ, ᅬ, ᅯ, ᅰ, ᅱ, ᅴ / ᅶ, ᅷ, ᅸ, ᅹ, ᅺ, ᅻ, ᅼ, ᅽ, ᅾ, ᅿ, ᆀ, ᆁ, ᆄ, ᆅ, ᆆ, ᆈ, ᆉ, ᆊ, ᆋ, ᆌ, ᆎ, ᆏ, ᆐ, ᆑ, ᆒ, ᆔ, ᆗ, ᆚ, ᆛ, ᆜ, ᆟ, ᆡ, ᆣ, ᆤ, ᆦ, ᆧ, ힰ, ힲ, ힳ, ힴ, ힵ, ힶ, ힷ, ힹ, ힺ, ힻ, ힽ, ퟁ, ퟂ, ퟃ, ퟅ, ퟆ] + any T
ljmo04: same as ljmo01, but without T
ljmo05: same as ljmo02, but without T
ljmo06: same as ljmo03, but without T

vjmo01: when followed by a T
vjmo02: when not followed by a T

tjmo01: when preceded by [ᅡ, ᅣ, ᅪ / ᆄ, ᆉ, ᆎ, ᆦ, ힲ, ힹ, ퟅ]
tjmo02: when preceded by [ᅥ, ᅧ, ᅬ, ᅯ, ᅱ, ᅴ, ᅵ / ᅿ, ᆆ, ᆈ, ᆏ, ᆑ, ᆔ, ᆝ, ᆟ, ᆡ, ᆥ, ힰ, ힴ, ힵ, ힺ]
tjmo03: when preceded by [ᅢ, ᅤ, ᅦ, ᅨ, ᅫ, ᅰ / ᆀ, ᆁ, ᆅ, ᆊ, ᆌ, ᆐ, ᆒ, ᆘ, ᆙ, ᆧ, ힳ, ힶ, ힷ, ힻ, ힾ, ힿ, ퟀ, ퟄ, ퟆ]
tjmo04: when preceded by [ᅩ, ᅭ, ᅮ, ᅲ, ᅳ / ᅠ (jungseong filler), ᅶ, ᅷ, ᅸ, ᅹ, ᅺ, ᅻ, ᅼ, ᅽ, ᅾ, ᆂ, ᆃ, ᆇ, ᆋ, ᆍ, ᆓ, ᆕ, ᆖ, ᆗ, ᆚ, ᆛ, ᆜ, ᆞ, ᆠ, ᆢ, ᆣ, ᆤ, ힱ, ힸ, ힼ, ힽ, ퟁ, ퟂ, ퟃ]

**Comment by acuteaccent** [comment]
Examples for testing

ljmo01: Lᆘᇫ
ljmo02: Lᆞᇫ
ljmo03: Lᅶᇫ
ljmo04: Lᆘ
ljmo05: Lᆞ
ljmo06: Lᅶ

vjmo01: ᅀVᇫ
vjmo02: ᅀV

tjmo01: ᅀᆄT
tjmo02: ᅀᅿT
tjmo03: ᅀᆀT
tjmo04: ᅀᅶT

**Comment by kenlunde** [comment]
Thank you for confirming the fixes.

**Comment by kenlunde** [comment]
Consolidated with Issue #27.
