### ISSUE TITLE
[Q] Source Han Serif's stance on Chinese full-width em dash?

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#63]
(Despite the place I open this issue, this question also applicable to Source Han Sans.)

Usage of Chinese's em dash, or 破折號 as well call it, is similar to that in English. A 破折號 is a horizontal line that “occupies the space of two characters in the center of the line” (from Wikipedia). So here's what I want:

![shs-em-1](https://cloud.githubusercontent.com/assets/959433/26790388/2045c024-4a46-11e7-8b05-2255c5c0c588.png)

The Chinese em dash has the following characteristics:
1. The glyph is center aligned with other CJK characters vertically.
2. There should be a single, unbroken horizontal line across the space of two characters.

## The usual ways

There are two typical ways to achieve this Chinese em dash:
1. use two U+2500 “─” Box Drawings Light Horizontal characters, i.e. ──
2. use two U+2014 “—” Em dash characters, i.e. ——

The first way is almost always guaranteed to work, but IIUC U+2500 isn't meant for such a  purpose. The second way makes more sense and ought to be supposed way, but depends heavily on the typeface design to achieve the desired result:

![shs-em-2](https://cloud.githubusercontent.com/assets/959433/26790396/274886e0-4a46-11e7-8e80-b0db67ffcea9.png)

Some fonts, like those released by Monotype, make U+2014 so that it looks just like U+2500, so getting the Chinese em dash is a piece of cake. Others have space in U+2014 so two U+2014 appears broken. We can only use U+2500 for those fonts (unless with the help of publishing software like InDesign).

## Situation in Source Han Serif

When using Source Han Serif I wanted to achieve what I want with a double U+2014 (instead of U+2500), but without much success.

![shs-em-3](https://cloud.githubusercontent.com/assets/959433/26790403/2d2e3f96-4a46-11e7-9c2e-1d9db2fdd615.png)

1. U+2014 doesn't occupy the whole container. So 2 x U+2014 won't make a joined horizontal line.
2. Two U+2014 is shorter than two full-width CJK characters (may not be a big deal).
3. U+2014 also looks a bit off when using it with Chinese characters. Unlike other Chinese fonts listed above, SHS obviously favors English typesetting when designing this glyph.

Source Han Serif provides another option which is U+2E3A. In fact, in supported applications, the OpenType ccmp feature replaces the double U+2014 with the glyph of U+2E3A. U+2E3A somewhat solves the "two lines should appear joined" problem, but (1) it is still shorter than 2 full-width CJK characters; and (2) it is still not center-aligned with other CJK characters vertically.

<img src="https://cloud.githubusercontent.com/assets/959433/26790801/9e888182-4a47-11e7-841b-aa1bb55901d6.png" width="250"/>

For now the desired result could only be achieved in InDesign. So, it seems that the only way is to use U+2500, which isn't ideal.

## Closing

As a user, my concern is how to enter the Chinese em dash probably so that it looks good on browsers, and word processing software like Word. As Source Han fonts are pushing the limits in many ways, I would like to know if this is something that could be improved in the font itself, or is indeed an intended behavior (so that it is the various software using the font that should be improved/fixed), or there is actually a way which I am not aware of.

Thank you!

**Comment by kenlunde** [comment]
I can respond by stating 1) that U+2015 ― HORIZONTAL BAR is your friend; and 2) that you should carefully read the _The 'ccmp' GSUB Feature_ section that begins on page 18 of the official readme, particularly the table at the bottom of page 19, and the paragraph at the top of page 20. Everything is pretty much explained and laid out there.

**Comment by tamcy** [comment]
Thanks for the reply. Ah, I actually read the readme file, but just couldn't recall it when I encounter the reported issue. So... yeah, probably not reading carefully enough. Sorry for that.

**Comment by kenlunde** [comment]
Handling U+2014 and U+2015, along with U+2E3A and U+2E3B, is a bit tricky, which is why I implemented their glyphs in the _Source Han_ families the way I did, which gives more than one pathway or method to access the desired form.
