### ISSUE TITLE
Regular weight unavailable in MS Office 2010

### ISSUE THREAD

**Issue by Pal3love** [adobe-fonts/source-han-serif#65]
This is might be a bug under MS Office **2010**. I found for OpenType CFF fonts, when style linking is set between the regular and bold weight but preferred family and preferred subfamily value are both omitted (i.e. exactly the same case for Source Han Serif Regular and Bold), MS Office **2010** apps including Word, Excel, PowerPoint would forcibly call the bold weight no matter the "bold" button is turned on or off. In other words, the regular weight can never be used.

![_20170619114444](https://user-images.githubusercontent.com/8181271/27268854-fa5c6602-54e4-11e7-8098-f8d6ca1ca9aa.png)

My solution of this issue is pretty simple (although I don't know why it works); by just adding complete preferred family and preferred subfamily info into both regular and bold weight we can easily fix it. So I was wondering if it could be done in the next update. Thanks!

(Later version of MS Office, such as 2013, 2016, etc., does not have this problem.)

**Comment by kenlunde** [comment]
Given that this is obviously a bug in an old version of MS Office, I don't see the point of hampering the fonts for more current versions of MS Office that do not exhibit this bug. Style-linking the Regular weight to the Bold weight was intentionally done for _Source Han Serif_ (from Version 1.000), and will be also done to _Source Han Sans_ (for Version 2.000).
