### ISSUE TITLE
Kana and Hangul in vertical layout with locl feature

### ISSUE THREAD

**Issue by jimmymasaru** [adobe-fonts/source-han-serif#66]
Source Han Serif has an issue in feature files that cause browsers not being able to render kana and old hangul correctly in vertical layout if a local (`lang` attribute) is specified. Although this might be the rendering engines' bugs but a very simple workaround can solve it.

Chrome:
<img width="745" alt="chrome" src="https://user-images.githubusercontent.com/12769660/28238539-58551554-69aa-11e7-860b-f1f8cb36b66c.png">

Firefox:
<img width="815" alt="firefox" src="https://user-images.githubusercontent.com/12769660/28238544-61d08fbe-69aa-11e7-87ec-5b725ff82ec6.png">

After updating feature files, they look like these.
Chrome:
<img width="741" alt="chrome-after" src="https://user-images.githubusercontent.com/12769660/28238546-709cb3f6-69aa-11e7-9418-cfed3bbe14f1.png">

Firefox:
<img width="800" alt="firefox-after" src="https://user-images.githubusercontent.com/12769660/28238547-733d32b6-69aa-11e7-986d-7e3ce29a630a.png">

It's worth mentioning that browsers still have their own bugs in rendering these texts.
- Chrome has some bugs regarding locl substitution of the full-width semicolon.
- Both Chrome and Firefox do not handle quotations correctly.
- Safari does not support locl features at all so there's no need to care at the moment.

## Fixes
Replace the languagesystem section in feature files with this section:
```
languagesystem DFLT dflt;
languagesystem hani dflt;
languagesystem hani ZHS;
languagesystem hani ZHT;
languagesystem hani ZHH;
languagesystem hani JAN;
languagesystem hani KOR;
languagesystem kana dflt;
languagesystem kana JAN;
languagesystem kana KOR;
languagesystem kana ZHS;
languagesystem kana ZHT;
languagesystem kana ZHH;
languagesystem hang dflt;
languagesystem hang KOR;
languagesystem hang JAN;
languagesystem hang ZHS;
languagesystem hang ZHT;
languagesystem hang ZHH;
languagesystem latn dflt;
languagesystem grek dflt;
languagesystem cyrl dflt;
```

[Test HTML File](https://gist.github.com/jimmymasaru/a81e56bb27415c9f24e9a58ed23b0f62)

## Others
I suggest Source Han Sans be fixed in the same way.

**Comment by kenlunde** [comment]
Thank you. In other words, I should add the following _languagesystem_ entries to the "features" files for both families:

```languagesystem kana KOR;
languagesystem kana ZHS;
languagesystem kana ZHT;
languagesystem kana ZHH;
languagesystem hang JAN;
languagesystem hang ZHS;
languagesystem hang ZHT;
languagesystem hang ZHH;
