### ISSUE TITLE
How To Use It In AutoCAD

### ISSUE THREAD

**Issue by chywu** [adobe-fonts/source-han-serif#69]
I love this font , but It seems that AutoDesk AutoCAD supports TTF fonts only .
Do you have a TTF version , or How can I make a TTF  version ?
Thank you !

**Comment by kenlunde** [comment]
While we have no plans to develop/deploy TTFs, and go [here](https://github.com/be5invis/source-han-sans-ttf/) to see how you can do it yourself. cc @be5invis

**Comment by be5invis** [comment]
@chywu I suggest you just to download the prebuilt, since building SHS-TTF from OTFs need a **really good computer**. (I used server clusters...)

**Comment by kenlunde** [comment]
@be5invis This person is asking about _Source Han_ **Serif**, not _Source Han_ **Sans**.

**Comment by be5invis** [comment]
@kenlunde @chywu For SERIF you can simply:

```bash
otfccdump xxx.otf | otfcc-c2q | otfccbuild -o xxx.ttf -O3 -s --keep-average-char-width
```

This is much faster but no hinting data.

**Comment by chywu** [comment]
I'll try it , Thank you all .

**Comment by Explorer09** [comment]
I thought a quick Googling will save you all the trouble of asking.
Well, someone has built a TTF version for you, unofficial, of course:
https://github.com/junmer/source-han-serif-ttf

**Comment by chywu** [comment]
Yes , Google is a great tool , but unfortunately Google cannot be connected here.
I used bing.com but it did not give me the right answer .
Thank you @Explorer09 . I am downloading that version .

**Comment by Pal3love** [comment]
As a alternative solution, I have also converted all Source Han Fonts into TrueType format with UPM 2048 and full-range sub-pixel anti-aliasing rendering: https://github.com/Pal3love/Source-Han-TrueType

You can simply download and try it :-)

**Comment by Explorer09** [comment]
@Pal3love 
Thank you of all your afforts, however, how are you sure that your conversion is lossless? I mean, doesn't TrueType support only quadratic Bézier curves, while OpenType support cubic Bézier curves (Type 1 outlines) and it's mathematically impossible to convert cubic Bézier to quadratic without loss.

Beside the question, I would like to see all the TTF conversion projects to work together :).

**Comment by be5invis** [comment]
@Explorer09 The difference is below the resolution (1/2048 em).

**Comment by Explorer09** [comment]
@be5invis I would not count that as _lossless_, but almost lossless, with losses below the designed font resolution.

**Comment by Explorer09** [comment]
@be5invis 
I would not count that as lossless, but almost lossless, with losses below the designed font resolution.
Consider this: Even the designed resolution is 2048 units per em, there are still use cases where the differences could matter. Take large signage (where a character might be printed with more than 2 meters in length, and the millimeter differences are observable), for example.

**Comment by Pal3love** [comment]
You are right, @Explorer09 . In its essence, my project is _almost_ lossless. However, I have minimize the difference within 1/2048 em and I believe such a difference is much negligible compared to the deviation from typography design to its implementation. Under special circumstances such as printing huge posters on which every single character is up to 2 meters width, we can definitely take advantage from the original version if absolute precision is strictly enforced.
