### ISSUE TITLE
Bopomofo characters need to be changed or adjusted

### ISSUE THREAD

**Issue by jimmymasaru** [adobe-fonts/source-han-serif#7]
Bopomofo letter V, NG and GN don't have the same designs as others. 
<img width="960" alt="screen shot 2017-04-04 at 22 03 05" src="https://cloud.githubusercontent.com/assets/12769660/24651639/ac3c4098-1982-11e7-8373-fae7355b41e3.png">

**Comment by jimmymasaru** [comment]
Besides, Bopomofo letters seem to be thinner than kana and hangul.

**Comment by kenlunde** [comment]
I, too, am not completely happy with the glyphs for bopomofo. Thank you for reporting this.

**Comment by ShikiSuen** [comment]
Typical manner of SinoType. They always do less efforts to non-ideograph Unicode characters. Just see their fonts shipped with macOS in recent years. I could see their potential effort on MOE-standard Chinese fonts (Kaisho, Socho, etc.), but their fonts are always terrible choices to show Japanese contents, bopomofo annotations, etc.

**Comment by chitsaou** [comment]
Also, U+312D (ㄭ) is not just a 180-degree rotate of U+3113 (ㄓ). 

Although the strokes of U+312D is not described in [the phonetic symbols manual](http://language.moe.gov.tw/001/Upload/files/site_content/M0001/juyin/html_en/index.html), it definitely should follow strokes of general kaishu style.

Sorry if this should go to another issue.

**Comment by kenlunde** [comment]
@chitsaou: I like consolidating issues, so I edited the title to broaden its scope.

**Comment by justinrleung** [comment]
Also, why is U+312F already filled in? It's not even added in Unicode 10.0.0.

**Comment by kenlunde** [comment]
@justinrleung: Due to the timing of the acceptance of U+312F, this character missed the cut for Unicode Version 10.0 (June, 2017), so it'll show up in Unicode Version 11.0 (June, 2018). It was deemed stable enough to include. Pardon the mild humor, but you are free to ignore U+312F until June of 2018. Also, hopefully an improved set of glyphs for bopomofo will be part of the typeface design by then.

**Comment by ShikiSuen** [comment]
@kenlunde I still think it could be better to ask a font company in Tawian to rebuild all bopomofo glyphs for both SHSans and SHSerif. I don't think SinoType is capable of doing this little part anymore.

**Comment by Buernia** [comment]
By the way, I think the glyphs of bopomofo and [Suzhou numerals](https://en.wikipedia.org/wiki/Suzhou_numerals) in Source Han Sans are also bad.

(Suzhou numerals in Source Han Serif are also need to be changed, especially the numeral 〥.)

I tried to redesign some of them a year ago:
![Redesigned version](http://b1.loli.io/images/p6eaB.png)

**Comment by kenlunde** [comment]
Consolidated with Issue #36.
