### ISSUE TITLE
Invalid substitute glyph indices?

### ISSUE THREAD

**Issue by winjii** [adobe-fonts/source-han-serif#70]
Regarding single-substitution information in the font data, the first of SourceHanSerifOTC_EL-M\SourceHanSerif-Regular.ttc collection, the following output glyph indices look to be out of the range of glyph index. Perhaps, some else font data be the same.

- At LookupList[31] (0-indexed), Coverage->GlyphIDs[0] + DeltaGlyphID >= 65535
- At LookupList[53], Coverage->GlyphIDs[0] + DeltaGlyphID < 0

I don't understand what these values mean.

**Comment by kenlunde** [comment]
What tool spit out that information? While the _Source Han_ fonts push various various implementation limits, such as the maximum number of glyphs, they do not exceed them. I therefore suspect that you're dealing with a tool issue, not a font issue. If you were to provide details about the tool that you used, I could potentially be more helpful, especially if I am familiar with the tool that you used.

**Comment by winjii** [comment]
I observed the problem with the two tools.

- T2FAnalyzer http://vanillasky-room.cocolog-nifty.com/blog/t2fanalyzer-truetypeopent.html
- FreeType2.8.1 https://www.freetype.org/
    - I use Visual Studio 2017, v141 toolset, and freetype-2.8/build/windows/vc2010/freetype.vcxproj to build.
    - I contained otvalid.c in the project, and added "FT_USE_MODULE( FT_Module_Class, otv_module_class )" to ftmodule.h, in order to use FT_OpenType_Validate() method.
    - Calling FT_OpenType_Validate(), the invalid indices appeared on otvgsub.c, line 73.

```
	FT_Library library;
	FT_Face face;

	FT_Init_FreeType(&library);
	FT_New_Face(library, "[suitable path]/SourceHanSerifOTC_EL-M/SourceHanSerif-Regular.ttc", 0, &face);

	FT_Bytes baseTable, gdefTable, gposTable, gsubTable, jstfTable;
	int error = FT_OpenType_Validate(face, FT_VALIDATE_GSUB, &baseTable, &gdefTable, &gposTable, &gsubTable, &jstfTable); //returns 8
```

**Comment by kenlunde** [comment]
My best guess is that _T2FAnalyzer_ doesn't support font collections, and also that the FreeType module that you tried also doesn't support collections. I suggest that you repeat these tests with the non-collection font resources whose filename extension is _otf_, not _ttc_. Everything about how the fonts were built and being used suggests that the problem is not with the fonts.

**Comment by winjii** [comment]
The two tools indicated exactly the same problem in OTF/Japanese/SourceHanSerif-Regular.otf. I'll check it in different ways. (If you are available, please give me some advice about reliable tools or something.)

**Comment by kenlunde** [comment]
The two lookup indexes, 31 and 53, seem to correspond to the 'hist' and 'calt' GSUB features, respectively, and they are unique in that they include a single substitution. The GIDs that are referenced are well within range, so I suspect that it is a bug someone in the tools that you are using. I recall that a bug that was exposed by the 'hist' GSUB feature, and perhaps @behdad remembers the details.

**Comment by winjii** [comment]
I made DTL OTMaster Light scan the otf file. Then, I saw that the two output GIDs was 1683 and 62249. 1683 equals "Coverage->GlyphIDs[0](=64605) + DeltaGlyphID(=2614) - 65536" at LookupList[31], and 62249 equals "Coverage->GlyphIDs[0](=1) + DeltaGlyphID(=-3288) + 65536" at LookupList[53].

In the page related to cmap table, Microsoft Typography, I also found the description such as the following.

https://www.microsoft.com/typography/otspec/cmap.htm#format2
"Finally, if the value obtained from the subarray is not 0 (which indicates the missing glyph), you should add idDelta to it in order to get the glyphIndex. The value idDelta permits the same subarray to be used for several different subheaders. The idDelta arithmetic is modulo 65536."

However, In the page related to Single Substitution Subtable, I didn't find such description.
https://www.microsoft.com/typography/otspec/gsub.htm#SSF1
However, still, I have conjectured that GID in this case implicitly is treated as the residue class ring of integers modulo 2^16.


I'm afraid that It became a topic uninvolved with Source Han Serif. It wouldn't be a problem if you should close this, because It was solved to me.
Thank you!

**Comment by kenlunde** [comment]
Your wish is my command.

**Comment by behdad** [comment]
GSUB SingleSubst math is also modulo 65536, but undocumented indeed.

**Comment by behdad** [comment]
cc @PeterCon
