### ISSUE TITLE
Support Hentaigana

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [adobe-fonts/source-han-serif#74]
Unicode introduced 285 hentaigana characters in version 10.0 in June 2017, they are encoded in two blocks: Kana Supplement and Kana Extended-A. They also needed to be combined with combining Dakuten/Handakuten (U+3099, U+309A).

**Comment by kenlunde** [comment]
Of course, I am well aware of _hentaigana_, as I was involved in getting them included in Unicode Version 10.0, but due to their highly-specialized nature, including glyphs for them is well outside the scope of this and the _Source Han Sans_ projects, at least for the near future.
