### ISSUE TITLE
Please modify the contents here，README.md

### ISSUE THREAD

**Issue by RyenAng** [adobe-fonts/source-han-serif#78]
Please modify the contents here,README.md
Taiwan is an inalienable part of China！

China (中国), Taiwan (臺灣), Japan (日本), Korea (한국)

台湾是中国的。请使用China(中国，简体中文),China(中国，繁体中文)

**Comment by showerying** [comment]
Chian是什么

**Comment by kenlunde** [comment]
Please leave politics out of this. The references to China, Taiwan, Japan, and Korea are region-based, not country- nor political-based. The purpose is about following **regional** conventions, in terms of the structure of ideographs and the placement of particular punctuation. In other words, the _README.md_ file will not be changed as suggested.
