### ISSUE TITLE
Open-source the "stroke library"

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-han-serif#79]
I've heard ([1]) that there is a stroke library containing 187 elemental stroke components, present in some sort of parametric form. So are there any plans to open-source it?

[1]: https://thetype.com/2017/04/11961/

**Comment by kenlunde** [comment]
We have no plans at the moment to open-source the _Source Han Serif_ (and, by extension, _Source Han Sans_) Element Libraries. At some point, which means not in the near future, we may be able to do so. Currently, there are both business and technical reasons why we cannot.
