### ISSUE TITLE
Install source-han-serif in ubuntu16.04 failed.

### ISSUE THREAD

**Issue by superPershing** [adobe-fonts/source-han-serif#80]
I want to install source-han-serif in my Ubuntu 16.04.6 LTS.  
I download this release: <https://github.com/adobe-fonts/source-han-serif/releases/download/1.001R/SourceHanSerif.ttc>

I try to use font viewer to install source-han-serif with GUI and mouse. But the font viewer show install failed quicky.  
![Screenshot from 2019-04-18 15-23-49](https://user-images.githubusercontent.com/15770165/56343787-46d53780-61ee-11e9-85f4-a8072f4cc519.png)
Then I read this link: <https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-8967116>, move font to `/usr/share/fonts` or `~/.fonts`, then run `sudo fc-cache`, but when I use `fc-list` command to view all my installed fonts, no source-han-serif found there.

**Comment by kenlunde** [comment]
@superPershing It would help to know which particular font resource, indicated by exact file name, that you are trying to install. With that said, I have zero experience with font installation on Linux, so hopefully someone in the community can offer suggestions or work-arounds. I found [this article](https://itsfoss.com/install-fonts-ubuntu-1404-1410/), but I am not sure whether it's helpful for you.

**Comment by superPershing** [comment]
@kenlunde I just download font from release page: <https://github.com/adobe-fonts/source-han-serif/releases/download/1.001R/SourceHanSerif.ttc>. I'm sorry that I didn't describe it detailedly.

**Comment by kenlunde** [comment]
That's a 28-font OpenType Collection, and is likely the problem. Try downloading and installing the individual [OTFs](https://github.com/adobe-fonts/source-han-serif/tree/release/OTF).

**Comment by kenlunde** [comment]
Also, the [release](https://github.com/adobe-fonts/source-han-serif/tree/release) branch has information about the various deployment formats, and download links.

**Comment by Explorer09** [comment]
@superPershing 
1. Did you check the integrity of the file you downloaded? You should get this if you check the SHA256 hash of the file (Source Han Serif 1.001, Super OTC deployment):

```
85cc634fa228286ca307803bbb4ca61f61fa821b3ed573f4f07c6f0c064426b5 *SourceHanSerif.ttc
```

2. Did your computer have any other instance of Source Han Serif installed?
3. When installing, did you leave any other application opened? (Especially your browser. That might be the cause of `fc-cache` failure.)

I did successfully install Source Han Serif in Super OTC deployment in Ubuntu 14.04. It's not that the operating system that doesn't support it, but something could be wrong with your installation procedure.

**Comment by superPershing** [comment]
@Explorer09 Thank you!
1.  My SHA256 hash of the file is the same to yours.
2.  [source-han-sans](https://github.com/adobe-fonts/source-han-sans) has been installed in my computer before. No other instance of  Source Han Serif installed.
3. I follow your suggestion an try again, close my Firefox and other applications. But it seems to no effect.

**Comment by superPershing** [comment]
By download this release: <https://github.com/adobe-fonts/source-han-serif/archive/1.001.zip> I install Source Han Serif success. Thank you very much!

**Comment by Jisu-Woniu** [comment]
Try using the OTF format files instead since there is possibility that Super OTC (.ttf in release page) is not currently supported in your system.
