### ISSUE TITLE
Could you support TTF font?

### ISSUE THREAD

**Issue by diguage** [adobe-fonts/source-han-serif#82]
Could you support TTF font?

**Comment by tamcy** [comment]
This has probably been answered in #69.

**Comment by miguelsousa** [comment]
@diguage you can use the `otf2ttf` tool from the [**AFDKO**](https://github.com/adobe-type-tools/afdko/) to convert any OTFs (or TTCs containing OTFs) to TrueType.

**Comment by diguage** [comment]
@miguelsousa 
Thank you very much. I'm googling the tool.
