### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by tamcy** [adobe-fonts/source-han-serif#84]
May I know if Source Han Serif v2.000 is still under development? Source Han Serif v2.000 is expected to contain the same changes in adobe-fonts/source-han-sans#253 (add the corresponding CMap entries to UTC-00791 and UTC-01312). More importantly, it will have a lot of enhancements to the current CJK glyph set, and will come with a long-anticipated HK version which has been long anticipated by Hong Kong people. Unlike Source Han Sans, the current TW version in v1.0 lacks a lot of HK characters, rendering it much less usable by the community.

Thank you.

**Comment by danrhatigan** [comment]
We are currently working on a major update to Source Han Serif that will allow it cover the support the same regions and languages as Source Han Sans. This update includes design revisions to a substantial number of Chinese glyphs, as well as the additions needed for support compatible with Source Han Sans. This work will likely continue into 2021.

**Comment by tamcy** [comment]
Understand that it involves a considerable amount of work. Thank you for the update and setting the expectation.
