### ISSUE TITLE
U+21B9 (↹, LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR) is incorrect

### ISSUE THREAD

**Issue by be5invis** [adobe-fonts/source-han-serif#86]
Source Han Sans mirror: https://github.com/adobe-fonts/source-han-sans/issues/260

### Prerequisites

* [X] If you are reporting an issue that affects glyphs for characters for a particular region or regions, did you verify that the characters are within the supported scope of the region or regions? This generally means GB 18030 or Tōngyòng Guīfàn Hànzìbiǎo (通用规范汉字表) for China, Big Five or CNS 11643 Planes 1 & 2 for Taiwan, HKSCS-2016 for Hong Kong (though support has been deferred until Version 2.000), the JIS standards for Japan, and KS X 1001 and KS X 1002 for Korea.
* [X] Did you thoroughly search the [open](https://github.com/adobe-fonts/source-han-serif/issues) and [closed](https://github.com/adobe-fonts/source-han-serif/issues?q=is%3Aissue+is%3Aclosed) issues to avoid reporting a duplicate issue?
* [X] Did you go through the [official font readme file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) to better understand the scope of the project, to include the *Known Issues* section at the very end?

### Description

The glyph for U+21B9 (↹, LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR) is incorrect in Source Han Serif.
![image](https://user-images.githubusercontent.com/240091/79927803-c1362a00-83f5-11ea-8227-d724d87ec9ec.png)

According to the code chart, this particular character has leftward arrow on top, rightward arrow on bottom.
![image](https://user-images.githubusercontent.com/240091/79927620-32c1a880-83f5-11ea-9b0a-d309b33e657c.png)

**Comment by punchcutter** [comment]
Source Han Sans also has the same issue.

**Comment by punchcutter** [comment]
Fixed in 2.000
<img width="152" alt="21B9" src="https://user-images.githubusercontent.com/11257204/140890157-1b385a1b-7d61-47dd-981a-d6790b1cee3c.png">
