### ISSUE TITLE
Discussion about U+58C4 (壄) 

### ISSUE THREAD

**Issue by Hulenkius** [adobe-fonts/source-han-serif#87]
In the Unicode standard chart 13.0 , U+58C4 (壄) is like below:

![](https://pic.downk.cc/item/5f2a826214195aa594e8b12c.png)

While in Source Han Serif and Source Han Sans, mistakes appear:

![](https://pic.downk.cc/item/5f2a826214195aa594e8b125.png)

This means, the G, T, K glyphs in the Serif and, K glyph in the Sans are mistaken.

The J glyph in the Chart has the same outline as U+21428:

![](https://pic.downk.cc/item/5f2a826214195aa594e8b12a.png)

**Comment by hatchzo** [comment]
Thanks, I will look them.
