### ISSUE TITLE
Fontconfig cannot handle Super OTC's `Source Han Serif Regular` and `Source Han Serif Bold`

### ISSUE THREAD

**Issue by trueroad** [adobe-fonts/source-han-serif#9]
I've noticed that fontconfig does not seem to be able to handle Super OTC's `Source Han Serif Regular` and `Source Han Serif Bold`.

```
$ fc-list "Source Han Serif"
/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc: 源ノ明朝,Source Han Serif:style=Regular
/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc: 源ノ明朝,Source Han Serif,Source Han Serif SemiBold,源ノ明朝 SemiBold:style=SemiBold,Regular
/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc: 源ノ明朝,Source Han Serif,Source Han Serif Light,源ノ明朝 Light:style=Light,Regular
/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc: 源ノ明朝,Source Han Serif,Source Han Serif ExtraLight,源ノ明朝 ExtraLight:style=ExtraLight,Regular
/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc: 源ノ明朝,Source Han Serif,Source Han Serif Heavy,源ノ明朝 Heavy:style=Heavy,Regular
/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc: 源ノ明朝,Source Han Serif:style=Bold
/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc: 源ノ明朝,Source Han Serif,Source Han Serif Medium,源ノ明朝 Medium:style=Medium,Regular
```

For Source Han Sans Super OTC, it is no problem.

```
$ fc-list "Source Han Sans"
/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc: 源ノ角ゴシック,Source Han Sans,Source Han Sans Bold,源ノ角ゴシック Bold:style=Bold,Regular
/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc: 源ノ角ゴシック,Source Han Sans,Source Han Sans Light,源ノ角ゴシック Light:style=Light,Regular
/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc: 源ノ角ゴシック,Source Han Sans,Source Han Sans Normal,源ノ角ゴシック Normal:style=Normal,Regular
/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc: 源ノ角ゴシック,Source Han Sans,Source Han Sans Regular,源ノ角ゴシック Regular:style=Regular
/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc: 源ノ角ゴシック,Source Han Sans,Source Han Sans Medium,源ノ角ゴシック Medium:style=Medium,Regular
/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc: 源ノ角ゴシック,Source Han Sans,Source Han Sans ExtraLight,源ノ角ゴシック ExtraLight:style=ExtraLight,Regular
/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc: 源ノ角ゴシック,Source Han Sans,Source Han Sans Heavy,源ノ角ゴシック Heavy:style=Heavy,Regular
```

If I understand correctly, the cause is that some names are inconsistent.
The names of `Regular` and `Bold` do not contain its weight name, others contain its weight name.

For Source Han Sans Super OTC, the names seem to be consistent.

Here is the inconsistent names I found.

* Index 0: SourceHanSerif-ExtraLight
  * Font Family name: Source Han Serif ExtraLight, 源ノ明朝 ExtraLight
  * Full font name: Source Han Serif ExtraLight, 源ノ明朝 ExtraLight
    * Both `Font Family name` and `Full font name` contain its weight name.
       It is no problem.

* Index 4: SourceHanSerif-Light
   * Font Family name: Source Han Serif Light, 源ノ明朝 Light
   * Full font name: Source Han Serif Light, 源ノ明朝 Light
     * Both `Font Family name` and `Full font name` contain its weight name.
        It is no problem.

* Index 8: SourceHanSerif-Regular
   * Font Family name: Source Han Serif, 源ノ明朝
   * Full font name: Source Han Serif, 源ノ明朝
     * Both `Font Family name` and `Full font name` do *not* contain its weight name.
       So fontconfig cannot select it.

* Index 12: SourceHanSerif-Medium
   * Font Family name: Source Han Serif Medium, 源ノ明朝 Medium
   * Full font name: Source Han Serif Medium, 源ノ明朝 Medium
     * Both `Font Family name` and `Full font name` contain its weight name.
        It is no problem.

* Index 16: SourceHanSerif-SemiBold
   * Font Family name: Source Han Serif SemiBold, 源ノ明朝 SemiBold
   * Full font name: Source Han Serif SemiBold, 源ノ明朝 SemiBold
     * Both `Font Family name` and `Full font name` contain its weight name.
        It is no problem.

* Index 20: SourceHanSerif-Bold
   * Font Family name: Source Han Serif, 源ノ明朝
   * Full font name: Source Han Serif Bold, 源ノ明朝 Bold
     * `Font Family name` does *not* contain its weight name.
       So fontconfig cannot select it.

* Index 24: SourceHanSerif-Heavy
   * Font Family name: Source Han Serif Heavy, 源ノ明朝 Heavy
   * Full font name: Source Han Serif Heavy, 源ノ明朝 Heavy
      * Both `Font Family name` and `Full font name` contain its weight name.
         It is no problem.

**Comment by kenlunde** [comment]
The main difference between _Source Han Sans_ and _Source Han Serif_ is that the Regular weights in the latter are style-linked to the Bold weights. I cannot see this being an issue with the Super OTC, but rather a _fontconfig_ issue. It is highly likely that this is the first time that _fontconfig_ has been asked to support such a font, so it is not a shock that this issue arose. Un–style-linking the fonts is a nonstarter.

Also, when _Source Han Sans_ Version 2.000 is released, its Regular weights will also be style-linked to its Bold weights.

**Comment by trueroad** [comment]
Thank you for your description.
I understood that the way to specify the font has been changed by _style-link_.

I've noticed that the fonts can be specified in the following way by `fontconfig`.

```
$ fc-match -v "Source Han Serif:style=Regular" | grep -e file -e index -e postscript
        file: "/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc"(w)
        index: 8(i)(w)
        postscriptname: "SourceHanSerif-Regular"(w)

$ fc-match -v "Source Han Serif:style=Bold" | grep -e file -e index -e postscript
        file: "/home/trueroad/.local/share/fonts/SourceHanSerif/SourceHanSerif.ttc"(w)
        index: 20(i)(w)
        postscriptname: "SourceHanSerif-Bold"(w)

$ fc-match -v "Source Han Sans:style=Regular" | grep -e file -e index -e postscript
        file: "/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc"(w)
        index: 12(i)(w)
        postscriptname: "SourceHanSans-Regular"(w)

$ fc-match -v "Source Han Sans:style=Bold" | grep -e file -e index -e postscript
        file: "/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc"(w)
        index: 24(i)(w)
        postscriptname: "SourceHanSans-Bold"(w)
```

I used a font name containing a weight name.
Current `Source Han Sans` all weights can be specified by this way.

```
$ fc-match -v "Source Han Sans Regular" | grep -e file -e index -e postscript
        file: "/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc"(w)
        index: 12(i)(w)
        postscriptname: "SourceHanSans-Regular"(w)

$ fc-match -v "Source Han Sans Bold" | grep -e file -e index -e postscript
        file: "/home/trueroad/.local/share/fonts/SourceHanSans/SourceHanSans.ttc"(w)
        index: 24(i)(w)
        postscriptname: "SourceHanSans-Bold"(w)
```

But, `Source Han Serif` Regular and Bold cannot be specified by this way.
So I wrote this issue.

```
$ fc-match -v "Source Han Serif Regular" | grep -e file -e index -e postscript
        file: "/usr/share/texmf-dist/fonts/truetype/public/ipaex/ipag.ttf"(w)
        index: 0(i)(w)
        postscriptname: "IPAGothic"(w)

$ fc-match -v "Source Han Serif Bold" | grep -e file -e index -e postscript
        file: "/usr/share/texmf-dist/fonts/truetype/public/ipaex/ipag.ttf"(w)
        index: 0(i)(w)
        postscriptname: "IPAGothic"(w)
```

Anyway, I will use the former way instead of latter way.
Thank you.

**Comment by kenlunde** [comment]
Yes, when fonts are style-linked, it changes how they need to be specified in certain environments.
