### ISSUE TITLE
There is a problem with the design of some kanji.

### ISSUE THREAD

**Issue by fontdasu** [adobe-fonts/source-han-serif#90]
I checked all the kanji in the Japanese sub set with my own eyes.

For the kanji for "uni9747" and "uni9A33",
Like the failure of multiple masters
The glyph design is strange.

As far as I can see, there is a problem with fonts other than the thinnest weight font and the thick font.

It's a fatal problem, so I want you to fix it immediately.

![UP](https://user-images.githubusercontent.com/55616797/100994189-afc31c00-3599-11eb-9626-e154362a8688.png)

**Comment by RuixiZhang42** [comment]
This seems to be region/language specific. The CN glyph and TW glyph for uni9747 are correct (with 3 horizontal strokes at the bottom right), but the JP glyph for it is wrong (two of the strokes are smashed together). Probably an interpolation problem.

**Comment by punchcutter** [comment]
Yes, this was an interpolation issue that has been fixed for the next update.

**Comment by punchcutter** [comment]
Fixed in 2.000

![source-han-serif-90](https://user-images.githubusercontent.com/11257204/140921902-812d18e9-37ec-4122-b001-e0550208a96f.gif)
