### ISSUE TITLE
ExtraLight 准 U+51C6 has a small mistake

### ISSUE THREAD

**Issue by kooriookami** [adobe-fonts/source-han-serif#96]
There is a little bump in the circled area.
![image](https://user-images.githubusercontent.com/38392315/128635146-2f0f6a53-835c-42fc-bd75-91274cc36b9f.png)
![image](https://user-images.githubusercontent.com/38392315/128635215-8735c1ac-4c23-4b84-b794-3a44af58c381.png)

**Comment by punchcutter** [comment]
This has been fixed for the next update.

**Comment by punchcutter** [comment]
Fixed in 2.001
<img width="727" alt="source-han-serif-96" src="https://user-images.githubusercontent.com/11257204/193520659-bec73057-693e-45f3-87b2-486e38e0a54f.png">
