### ISSUE TITLE
最 Chinese character not "correct"?

### ISSUE THREAD

**Issue by rieje** [adobe-fonts/source-han-serif#97]
The character 最 (Chinese pinyin: zuì) in most cases look like [this](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2F9ejMvgCT_5U%2Fmaxresdefault.jpg&imgrefurl=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9ejMvgCT_5U&tbnid=QFse1UwnbVt-8M&vet=12ahUKEwiI2eTF7qfyAhVzBFkFHSwSCokQMygDegUIARC2AQ..i&docid=A2NnnoLSfJybsM&w=1280&h=720&q=%E6%9C%80&client=firefox-b-1-d&ved=2ahUKEwiI2eTF7qfyAhVzBFkFHSwSCokQMygDegUIARC2AQ) and seems to be the standard. However, the font shows as [this](https://www.google.com/imgres?imgurl=https%3A%2F%2Fimg.zdic.net%2Fkxzd%2F6700.svg&imgrefurl=https%3A%2F%2Fwww.zdic.net%2Fhans%2F%25E6%259C%2580&tbnid=_nR40ygYH_uwRM&vet=12ahUKEwiI2eTF7qfyAhVzBFkFHSwSCokQMygFegUIARC7AQ..i&docid=X1vO-4pgGf8DPM&w=800&h=800&q=%E6%9C%80&client=firefox-b-1-d&ved=2ahUKEwiI2eTF7qfyAhVzBFkFHSwSCokQMygFegUIARC7AQ#imgrc=_nR40ygYH_uwRM&imgdii=xol3MlHSu-ZajM) (1 horizontal line vs. vs 2 horiziontal lines on the top box).

Other fonts I've tried on Arch Linux do not have this problem but I much prefer this serif font to be as standard, pretty, and as easy to read as possible.

In searching through submitted issues to see if there's any relevant info, I came across [this](https://github.com/adobe-fonts/source-han-serif/issues/40#issuecomment-450832401) (see the mentioned issue) but I'm not technical to understand if it is indeed relevant or what exactly is the problem. If there's nothing "wrong", feel free to suggest a font that best respects "standard" CJK.

**Comment by tamcy** [comment]
Standard differs between languages and regions. I suggest you to first read the [official README file](https://github.com/adobe-fonts/source-han-serif/raw/release/SourceHanSerifReadMe.pdf) of the font, especially the "Overview", "Glyph Sharing Statistics" and the "Language Particulars" sections.

Here is how the character 最 looks like in different regions of this font:
![z](https://user-images.githubusercontent.com/959433/128964227-3b1e7436-8f21-4935-8b01-7f9abbb86c59.png)

**Comment by punchcutter** [comment]
What @tamcy said and there is one more IVD glyph to add to this list for Adobe-Japan1:
<img width="262" alt="uni6700e0101" src="https://user-images.githubusercontent.com/11257204/128966092-2c4ec09c-5b54-4cd5-9a68-4e02b3bfea85.png">
