### ISSUE TITLE
Mapping error for U+635C 捜

### ISSUE THREAD

**Issue by NightFurySL2001** [adobe-fonts/source-han-serif#98]
![image](https://user-images.githubusercontent.com/33471049/129440805-9ffa3f7d-2025-44ed-a8ea-c7477a1166b3.png)
Mapping for CN/TW should be changed to match JP/KR. The current glyph for CN/TW is different from U+641C 搜 though.
![image](https://user-images.githubusercontent.com/33471049/129441091-a73f8d6c-63c0-404b-ad5e-67cd0d5862ad.png)

P/S: The glyph for U+635C 捜 (CN/TW) is better than U+641C 搜.

Suggestion: remove the current glyph for U+641C 搜 in CN/TW, change the glyph mapping from current U+635C 捜 to U+641C 搜 for CN/TW, and change the glyph mapping for current U+635C 捜 in CN/TW to match JP/KR.

**Comment by punchcutter** [comment]
uni635C-CN has already been removed for the next update so everything will map to the JP glyph as it does in Sans. The design of U+641C has also been updated.
